// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dockpilot/product/v1/session.proto

// Product control-plane messages. Transport-specific HTTP/2 window, ALPN,
// metadata, and framing details are intentionally absent from this namespace.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SentAtUnixNano int64                  `protobuf:"varint,1,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

type Capability struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ConnectionReady       bool                   `protobuf:"varint,1,opt,name=connection_ready,json=connectionReady,proto3" json:"connection_ready,omitempty"`
	DockerReady           bool                   `protobuf:"varint,2,opt,name=docker_ready,json=dockerReady,proto3" json:"docker_ready,omitempty"`
	ComposeReady          bool                   `protobuf:"varint,3,opt,name=compose_ready,json=composeReady,proto3" json:"compose_ready,omitempty"`
	DockerApiVersion      string                 `protobuf:"bytes,4,opt,name=docker_api_version,json=dockerApiVersion,proto3" json:"docker_api_version,omitempty"`
	BundledComposeVersion string                 `protobuf:"bytes,5,opt,name=bundled_compose_version,json=bundledComposeVersion,proto3" json:"bundled_compose_version,omitempty"`
	Reason                string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// Filesystem capability is reported by the Agent, which owns the per-root
	// identical-path self-check (architecture 3.1 and 3.2). An Agent one protocol
	// version behind omits these fields; the Server then keeps its existing
	// "capability not reported" state rather than assuming access.
	FsRead        bool   `protobuf:"varint,7,opt,name=fs_read,json=fsRead,proto3" json:"fs_read,omitempty"`
	FsWrite       bool   `protobuf:"varint,8,opt,name=fs_write,json=fsWrite,proto3" json:"fs_write,omitempty"`
	FsReadReason  string `protobuf:"bytes,9,opt,name=fs_read_reason,json=fsReadReason,proto3" json:"fs_read_reason,omitempty"`
	FsWriteReason string `protobuf:"bytes,10,opt,name=fs_write_reason,json=fsWriteReason,proto3" json:"fs_write_reason,omitempty"`
	// metrics_matrix reports that this Agent can serve the host-scoped metrics
	// matrix stream. It is a capability rather than a protocol version because an
	// Agent built before the feature reports the same protocol version as one
	// built after, and so cannot be told apart by version. An Agent that does not
	// know this field leaves it false, which is the answer the Server needs.
	MetricsMatrix bool `protobuf:"varint,11,opt,name=metrics_matrix,json=metricsMatrix,proto3" json:"metrics_matrix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *Capability) GetConnectionReady() bool {
	if x != nil {
		return x.ConnectionReady
	}
	return false
}

func (x *Capability) GetDockerReady() bool {
	if x != nil {
		return x.DockerReady
	}
	return false
}

func (x *Capability) GetComposeReady() bool {
	if x != nil {
		return x.ComposeReady
	}
	return false
}

func (x *Capability) GetDockerApiVersion() string {
	if x != nil {
		return x.DockerApiVersion
	}
	return ""
}

func (x *Capability) GetBundledComposeVersion() string {
	if x != nil {
		return x.BundledComposeVersion
	}
	return ""
}

func (x *Capability) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Capability) GetFsRead() bool {
	if x != nil {
		return x.FsRead
	}
	return false
}

func (x *Capability) GetFsWrite() bool {
	if x != nil {
		return x.FsWrite
	}
	return false
}

func (x *Capability) GetFsReadReason() string {
	if x != nil {
		return x.FsReadReason
	}
	return ""
}

func (x *Capability) GetFsWriteReason() string {
	if x != nil {
		return x.FsWriteReason
	}
	return ""
}

func (x *Capability) GetMetricsMatrix() bool {
	if x != nil {
		return x.MetricsMatrix
	}
	return false
}

type HeartbeatResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ObservedAtUnixNano int64                  `protobuf:"varint,1,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	Capability         *Capability            `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatResponse) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

func (x *HeartbeatResponse) GetCapability() *Capability {
	if x != nil {
		return x.Capability
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *QueryRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *QueryRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ProjectKey    string                 `protobuf:"bytes,3,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *OperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OperationRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *OperationRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *OperationRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OperationResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Status                 string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Phase                  string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Revision               uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	PartialEffectsPossible bool                   `protobuf:"varint,4,opt,name=partial_effects_possible,json=partialEffectsPossible,proto3" json:"partial_effects_possible,omitempty"`
	Error                  string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	OutputTail             []byte                 `protobuf:"bytes,6,opt,name=output_tail,json=outputTail,proto3" json:"output_tail,omitempty"`
	OutputTruncated        bool                   `protobuf:"varint,7,opt,name=output_truncated,json=outputTruncated,proto3" json:"output_truncated,omitempty"`
	CancelMode             string                 `protobuf:"bytes,8,opt,name=cancel_mode,json=cancelMode,proto3" json:"cancel_mode,omitempty"`
	CanCancel              bool                   `protobuf:"varint,9,opt,name=can_cancel,json=canCancel,proto3" json:"can_cancel,omitempty"`
	CancelabilityReason    string                 `protobuf:"bytes,10,opt,name=cancelability_reason,json=cancelabilityReason,proto3" json:"cancelability_reason,omitempty"`
	RequestedAtUnixNano    int64                  `protobuf:"varint,11,opt,name=requested_at_unix_nano,json=requestedAtUnixNano,proto3" json:"requested_at_unix_nano,omitempty"`
	StartedAtUnixNano      int64                  `protobuf:"varint,12,opt,name=started_at_unix_nano,json=startedAtUnixNano,proto3" json:"started_at_unix_nano,omitempty"`
	FinishedAtUnixNano     int64                  `protobuf:"varint,13,opt,name=finished_at_unix_nano,json=finishedAtUnixNano,proto3" json:"finished_at_unix_nano,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *OperationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperationResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *OperationResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *OperationResponse) GetPartialEffectsPossible() bool {
	if x != nil {
		return x.PartialEffectsPossible
	}
	return false
}

func (x *OperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OperationResponse) GetOutputTail() []byte {
	if x != nil {
		return x.OutputTail
	}
	return nil
}

func (x *OperationResponse) GetOutputTruncated() bool {
	if x != nil {
		return x.OutputTruncated
	}
	return false
}

func (x *OperationResponse) GetCancelMode() string {
	if x != nil {
		return x.CancelMode
	}
	return ""
}

func (x *OperationResponse) GetCanCancel() bool {
	if x != nil {
		return x.CanCancel
	}
	return false
}

func (x *OperationResponse) GetCancelabilityReason() string {
	if x != nil {
		return x.CancelabilityReason
	}
	return ""
}

func (x *OperationResponse) GetRequestedAtUnixNano() int64 {
	if x != nil {
		return x.RequestedAtUnixNano
	}
	return 0
}

func (x *OperationResponse) GetStartedAtUnixNano() int64 {
	if x != nil {
		return x.StartedAtUnixNano
	}
	return 0
}

func (x *OperationResponse) GetFinishedAtUnixNano() int64 {
	if x != nil {
		return x.FinishedAtUnixNano
	}
	return 0
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Operation     *OperationResponse     `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *GetOperationResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetOperationResponse) GetOperation() *OperationResponse {
	if x != nil {
		return x.Operation
	}
	return nil
}

type CancelOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationRequest.ProtoReflect.Descriptor instead.
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CancelOperationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       string                 `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Operation     *OperationResponse     `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationResponse) Reset() {
	*x = CancelOperationResponse{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationResponse) ProtoMessage() {}

func (x *CancelOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationResponse.ProtoReflect.Descriptor instead.
func (*CancelOperationResponse) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOperationResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *CancelOperationResponse) GetOperation() *OperationResponse {
	if x != nil {
		return x.Operation
	}
	return nil
}

type ListActiveOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveOperationsRequest) Reset() {
	*x = ListActiveOperationsRequest{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveOperationsRequest) ProtoMessage() {}

func (x *ListActiveOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveOperationsRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{11}
}

type ActiveOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ProjectKey    string                 `protobuf:"bytes,3,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Operation     *OperationResponse     `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveOperation) Reset() {
	*x = ActiveOperation{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveOperation) ProtoMessage() {}

func (x *ActiveOperation) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveOperation.ProtoReflect.Descriptor instead.
func (*ActiveOperation) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *ActiveOperation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ActiveOperation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActiveOperation) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *ActiveOperation) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ActiveOperation) GetOperation() *OperationResponse {
	if x != nil {
		return x.Operation
	}
	return nil
}

type ListActiveOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*ActiveOperation     `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveOperationsResponse) Reset() {
	*x = ListActiveOperationsResponse{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveOperationsResponse) ProtoMessage() {}

func (x *ListActiveOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveOperationsResponse) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *ListActiveOperationsResponse) GetOperations() []*ActiveOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type LogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	TailLines     uint64                 `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	ShowStdout    bool                   `protobuf:"varint,4,opt,name=show_stdout,json=showStdout,proto3" json:"show_stdout,omitempty"`
	ShowStderr    bool                   `protobuf:"varint,5,opt,name=show_stderr,json=showStderr,proto3" json:"show_stderr,omitempty"`
	Timestamps    bool                   `protobuf:"varint,6,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	ProjectUid    string                 `protobuf:"bytes,7,opt,name=project_uid,json=projectUid,proto3" json:"project_uid,omitempty"`
	Services      []string               `protobuf:"bytes,8,rep,name=services,proto3" json:"services,omitempty"`
	Since         string                 `protobuf:"bytes,9,opt,name=since,proto3" json:"since,omitempty"`
	Until         string                 `protobuf:"bytes,10,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{14}
}

func (x *LogStreamRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LogStreamRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogStreamRequest) GetTailLines() uint64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogStreamRequest) GetShowStdout() bool {
	if x != nil {
		return x.ShowStdout
	}
	return false
}

func (x *LogStreamRequest) GetShowStderr() bool {
	if x != nil {
		return x.ShowStderr
	}
	return false
}

func (x *LogStreamRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

func (x *LogStreamRequest) GetProjectUid() string {
	if x != nil {
		return x.ProjectUid
	}
	return ""
}

func (x *LogStreamRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *LogStreamRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *LogStreamRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

type LogEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Data              []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Stream            string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	LineCount         uint64                 `protobuf:"varint,3,opt,name=line_count,json=lineCount,proto3" json:"line_count,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,4,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	DroppedBytes      uint64                 `protobuf:"varint,5,opt,name=dropped_bytes,json=droppedBytes,proto3" json:"dropped_bytes,omitempty"`
	DroppedLines      uint64                 `protobuf:"varint,6,opt,name=dropped_lines,json=droppedLines,proto3" json:"dropped_lines,omitempty"`
	Terminal          bool                   `protobuf:"varint,7,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Error             string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{15}
}

func (x *LogEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogEvent) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEvent) GetLineCount() uint64 {
	if x != nil {
		return x.LineCount
	}
	return 0
}

func (x *LogEvent) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogEvent) GetDroppedBytes() uint64 {
	if x != nil {
		return x.DroppedBytes
	}
	return 0
}

func (x *LogEvent) GetDroppedLines() uint64 {
	if x != nil {
		return x.DroppedLines
	}
	return 0
}

func (x *LogEvent) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *LogEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsStreamRequest) Reset() {
	*x = StatsStreamRequest{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsStreamRequest) ProtoMessage() {}

func (x *StatsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsStreamRequest.ProtoReflect.Descriptor instead.
func (*StatsStreamRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{16}
}

func (x *StatsStreamRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

// MetricsMatrixRequest opens the host-scoped metrics stream. It carries no
// selector: the frame is the whole host, and narrowing is the viewer's job.
type MetricsMatrixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsMatrixRequest) Reset() {
	*x = MetricsMatrixRequest{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsMatrixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsMatrixRequest) ProtoMessage() {}

func (x *MetricsMatrixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsMatrixRequest.ProtoReflect.Descriptor instead.
func (*MetricsMatrixRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{17}
}

// ManagedFilesystem is capacity for a path Dockpilot writes to - a discovery
// root or the Agent state directory - deduplicated by filesystem. It is not an
// inventory of the host's mounts.
type ManagedFilesystem struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Path       string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TotalBytes uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes  uint64                 `protobuf:"varint,3,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	// unavailable is this one path failing to answer - a discovery root that has
	// gone, or one the Agent cannot stat. It is a fact about the path, and must
	// not take the rest of the workload summary with it.
	Unavailable   bool   `protobuf:"varint,4,opt,name=unavailable,proto3" json:"unavailable,omitempty"`
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedFilesystem) Reset() {
	*x = ManagedFilesystem{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedFilesystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedFilesystem) ProtoMessage() {}

func (x *ManagedFilesystem) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedFilesystem.ProtoReflect.Descriptor instead.
func (*ManagedFilesystem) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{18}
}

func (x *ManagedFilesystem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ManagedFilesystem) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ManagedFilesystem) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *ManagedFilesystem) GetUnavailable() bool {
	if x != nil {
		return x.Unavailable
	}
	return false
}

func (x *ManagedFilesystem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// WorkloadSummary is the Docker workload this Agent manages, against the
// capacity the Engine reports. It is deliberately not host OS metrics: the
// Agent runs in a container, where /proc/net is the container's own network
// namespace, so host network read there would be the Agent's own traffic
// wearing the host's name. Capacity comes from the Engine because the daemon
// runs on the host and its answer does not change with the reader's namespace.
type WorkloadSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuCapacity       uint32                 `protobuf:"varint,1,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	MemoryCapacity    uint64                 `protobuf:"varint,2,opt,name=memory_capacity,json=memoryCapacity,proto3" json:"memory_capacity,omitempty"`
	ContainersRunning uint32                 `protobuf:"varint,3,opt,name=containers_running,json=containersRunning,proto3" json:"containers_running,omitempty"`
	ContainersTotal   uint32                 `protobuf:"varint,4,opt,name=containers_total,json=containersTotal,proto3" json:"containers_total,omitempty"`
	Filesystems       []*ManagedFilesystem   `protobuf:"bytes,5,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkloadSummary) Reset() {
	*x = WorkloadSummary{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSummary) ProtoMessage() {}

func (x *WorkloadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSummary.ProtoReflect.Descriptor instead.
func (*WorkloadSummary) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{19}
}

func (x *WorkloadSummary) GetCpuCapacity() uint32 {
	if x != nil {
		return x.CpuCapacity
	}
	return 0
}

func (x *WorkloadSummary) GetMemoryCapacity() uint64 {
	if x != nil {
		return x.MemoryCapacity
	}
	return 0
}

func (x *WorkloadSummary) GetContainersRunning() uint32 {
	if x != nil {
		return x.ContainersRunning
	}
	return 0
}

func (x *WorkloadSummary) GetContainersTotal() uint32 {
	if x != nil {
		return x.ContainersTotal
	}
	return 0
}

func (x *WorkloadSummary) GetFilesystems() []*ManagedFilesystem {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

// MetricsMatrixFrame is one complete picture of a host at one instant. The
// container rows and the summary are computed from a single membership
// snapshot, so a frame never disagrees with itself; a container that dies
// mid-assembly leaves in the next frame, not halfway through this one.
//
// Frames are the unit of loss. A slow consumer drops whole frames rather than
// individual samples, because a per-sample latest-wins over one multiplexed
// stream would let a busy container overwrite a quiet one indefinitely. Dropping
// a frame loses one round of everything and the next frame carries every
// container again.
type MetricsMatrixFrame struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ObservedAtUnixNano int64                  `protobuf:"varint,1,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	Workload           *WorkloadSummary       `protobuf:"bytes,2,opt,name=workload,proto3" json:"workload,omitempty"`
	Containers         []*StatsSample         `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	DroppedFrames      uint64                 `protobuf:"varint,4,opt,name=dropped_frames,json=droppedFrames,proto3" json:"dropped_frames,omitempty"`
	// membership_stale says the container rows are the last set the Agent could
	// confirm, not the current one, because refreshing them from the Engine
	// failed. Keeping the rows silently would assert they are current; dropping
	// them would say the host has no containers. A failed listing means
	// membership is unknown, which is neither, and this is how it is said.
	MembershipStale  bool   `protobuf:"varint,5,opt,name=membership_stale,json=membershipStale,proto3" json:"membership_stale,omitempty"`
	MembershipReason string `protobuf:"bytes,6,opt,name=membership_reason,json=membershipReason,proto3" json:"membership_reason,omitempty"`
	// pending_container_ids are in the membership snapshot but have not produced
	// a sample yet. Present-but-unreported is not the same as gone, and a slow
	// container must not delay the frame for the others.
	PendingContainerIds []string `protobuf:"bytes,7,rep,name=pending_container_ids,json=pendingContainerIds,proto3" json:"pending_container_ids,omitempty"`
	// workload_stale moves independently of membership_stale. Listing containers
	// and asking the Engine about its own capacity are different calls that fail
	// for different reasons; one frame-wide error would report a stale CPU count
	// as containers of unknown membership, or the reverse.
	WorkloadStale  bool   `protobuf:"varint,8,opt,name=workload_stale,json=workloadStale,proto3" json:"workload_stale,omitempty"`
	WorkloadReason string `protobuf:"bytes,9,opt,name=workload_reason,json=workloadReason,proto3" json:"workload_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsMatrixFrame) Reset() {
	*x = MetricsMatrixFrame{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsMatrixFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsMatrixFrame) ProtoMessage() {}

func (x *MetricsMatrixFrame) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsMatrixFrame.ProtoReflect.Descriptor instead.
func (*MetricsMatrixFrame) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{20}
}

func (x *MetricsMatrixFrame) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

func (x *MetricsMatrixFrame) GetWorkload() *WorkloadSummary {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *MetricsMatrixFrame) GetContainers() []*StatsSample {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *MetricsMatrixFrame) GetDroppedFrames() uint64 {
	if x != nil {
		return x.DroppedFrames
	}
	return 0
}

func (x *MetricsMatrixFrame) GetMembershipStale() bool {
	if x != nil {
		return x.MembershipStale
	}
	return false
}

func (x *MetricsMatrixFrame) GetMembershipReason() string {
	if x != nil {
		return x.MembershipReason
	}
	return ""
}

func (x *MetricsMatrixFrame) GetPendingContainerIds() []string {
	if x != nil {
		return x.PendingContainerIds
	}
	return nil
}

func (x *MetricsMatrixFrame) GetWorkloadStale() bool {
	if x != nil {
		return x.WorkloadStale
	}
	return false
}

func (x *MetricsMatrixFrame) GetWorkloadReason() string {
	if x != nil {
		return x.WorkloadReason
	}
	return ""
}

type StatsSample struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ContainerId        string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ObservedAtUnixNano int64                  `protobuf:"varint,2,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	CpuPercent         float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsage        uint64                 `protobuf:"varint,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryLimit        uint64                 `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	NetworkRx          uint64                 `protobuf:"varint,6,opt,name=network_rx,json=networkRx,proto3" json:"network_rx,omitempty"`
	NetworkTx          uint64                 `protobuf:"varint,7,opt,name=network_tx,json=networkTx,proto3" json:"network_tx,omitempty"`
	BlockRead          uint64                 `protobuf:"varint,8,opt,name=block_read,json=blockRead,proto3" json:"block_read,omitempty"`
	BlockWrite         uint64                 `protobuf:"varint,9,opt,name=block_write,json=blockWrite,proto3" json:"block_write,omitempty"`
	RestartCount       uint64                 `protobuf:"varint,10,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	Health             string                 `protobuf:"bytes,11,opt,name=health,proto3" json:"health,omitempty"`
	UptimeNano         int64                  `protobuf:"varint,12,opt,name=uptime_nano,json=uptimeNano,proto3" json:"uptime_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatsSample) Reset() {
	*x = StatsSample{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsSample) ProtoMessage() {}

func (x *StatsSample) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsSample.ProtoReflect.Descriptor instead.
func (*StatsSample) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{21}
}

func (x *StatsSample) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StatsSample) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

func (x *StatsSample) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *StatsSample) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *StatsSample) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *StatsSample) GetNetworkRx() uint64 {
	if x != nil {
		return x.NetworkRx
	}
	return 0
}

func (x *StatsSample) GetNetworkTx() uint64 {
	if x != nil {
		return x.NetworkTx
	}
	return 0
}

func (x *StatsSample) GetBlockRead() uint64 {
	if x != nil {
		return x.BlockRead
	}
	return 0
}

func (x *StatsSample) GetBlockWrite() uint64 {
	if x != nil {
		return x.BlockWrite
	}
	return 0
}

func (x *StatsSample) GetRestartCount() uint64 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *StatsSample) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *StatsSample) GetUptimeNano() int64 {
	if x != nil {
		return x.UptimeNano
	}
	return 0
}

type AuditCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incarnation   uint64                 `protobuf:"varint,1,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditCursor) Reset() {
	*x = AuditCursor{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditCursor) ProtoMessage() {}

func (x *AuditCursor) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditCursor.ProtoReflect.Descriptor instead.
func (*AuditCursor) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{22}
}

func (x *AuditCursor) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *AuditCursor) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type AuditRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Cursor             *AuditCursor           `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	AppendedAtUnixNano int64                  `protobuf:"varint,2,opt,name=appended_at_unix_nano,json=appendedAtUnixNano,proto3" json:"appended_at_unix_nano,omitempty"`
	Payload            []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{23}
}

func (x *AuditRecord) GetCursor() *AuditCursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *AuditRecord) GetAppendedAtUnixNano() int64 {
	if x != nil {
		return x.AppendedAtUnixNano
	}
	return 0
}

func (x *AuditRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AuditGap struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Incarnation      uint64                 `protobuf:"varint,1,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	FromSequence     uint64                 `protobuf:"varint,2,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	UntilSequence    uint64                 `protobuf:"varint,3,opt,name=until_sequence,json=untilSequence,proto3" json:"until_sequence,omitempty"`
	Reason           string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Precision        string                 `protobuf:"bytes,5,opt,name=precision,proto3" json:"precision,omitempty"`
	LastLossRevision uint64                 `protobuf:"varint,6,opt,name=last_loss_revision,json=lastLossRevision,proto3" json:"last_loss_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditGap) Reset() {
	*x = AuditGap{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditGap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditGap) ProtoMessage() {}

func (x *AuditGap) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditGap.ProtoReflect.Descriptor instead.
func (*AuditGap) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{24}
}

func (x *AuditGap) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *AuditGap) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *AuditGap) GetUntilSequence() uint64 {
	if x != nil {
		return x.UntilSequence
	}
	return 0
}

func (x *AuditGap) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditGap) GetPrecision() string {
	if x != nil {
		return x.Precision
	}
	return ""
}

func (x *AuditGap) GetLastLossRevision() uint64 {
	if x != nil {
		return x.LastLossRevision
	}
	return 0
}

type AuditCoverageSnapshot struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Revision                    uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	GeneratedAtUnixNano         int64                  `protobuf:"varint,2,opt,name=generated_at_unix_nano,json=generatedAtUnixNano,proto3" json:"generated_at_unix_nano,omitempty"`
	Gaps                        []*AuditGap            `protobuf:"bytes,3,rep,name=gaps,proto3" json:"gaps,omitempty"`
	CoverageUnknownIncarnations []uint64               `protobuf:"varint,4,rep,packed,name=coverage_unknown_incarnations,json=coverageUnknownIncarnations,proto3" json:"coverage_unknown_incarnations,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AuditCoverageSnapshot) Reset() {
	*x = AuditCoverageSnapshot{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditCoverageSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditCoverageSnapshot) ProtoMessage() {}

func (x *AuditCoverageSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditCoverageSnapshot.ProtoReflect.Descriptor instead.
func (*AuditCoverageSnapshot) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{25}
}

func (x *AuditCoverageSnapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *AuditCoverageSnapshot) GetGeneratedAtUnixNano() int64 {
	if x != nil {
		return x.GeneratedAtUnixNano
	}
	return 0
}

func (x *AuditCoverageSnapshot) GetGaps() []*AuditGap {
	if x != nil {
		return x.Gaps
	}
	return nil
}

func (x *AuditCoverageSnapshot) GetCoverageUnknownIncarnations() []uint64 {
	if x != nil {
		return x.CoverageUnknownIncarnations
	}
	return nil
}

type AuditBounds struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	WalFloor              *AuditCursor           `protobuf:"bytes,1,opt,name=wal_floor,json=walFloor,proto3" json:"wal_floor,omitempty"`
	WalCeiling            *AuditCursor           `protobuf:"bytes,2,opt,name=wal_ceiling,json=walCeiling,proto3" json:"wal_ceiling,omitempty"`
	NextCursor            *AuditCursor           `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	ServerAckedThrough    *AuditCursor           `protobuf:"bytes,4,opt,name=server_acked_through,json=serverAckedThrough,proto3" json:"server_acked_through,omitempty"`
	AcknowledgedArchiveId string                 `protobuf:"bytes,5,opt,name=acknowledged_archive_id,json=acknowledgedArchiveId,proto3" json:"acknowledged_archive_id,omitempty"`
	CoverageRevision      uint64                 `protobuf:"varint,6,opt,name=coverage_revision,json=coverageRevision,proto3" json:"coverage_revision,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AuditBounds) Reset() {
	*x = AuditBounds{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditBounds) ProtoMessage() {}

func (x *AuditBounds) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditBounds.ProtoReflect.Descriptor instead.
func (*AuditBounds) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{26}
}

func (x *AuditBounds) GetWalFloor() *AuditCursor {
	if x != nil {
		return x.WalFloor
	}
	return nil
}

func (x *AuditBounds) GetWalCeiling() *AuditCursor {
	if x != nil {
		return x.WalCeiling
	}
	return nil
}

func (x *AuditBounds) GetNextCursor() *AuditCursor {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

func (x *AuditBounds) GetServerAckedThrough() *AuditCursor {
	if x != nil {
		return x.ServerAckedThrough
	}
	return nil
}

func (x *AuditBounds) GetAcknowledgedArchiveId() string {
	if x != nil {
		return x.AcknowledgedArchiveId
	}
	return ""
}

func (x *AuditBounds) GetCoverageRevision() uint64 {
	if x != nil {
		return x.CoverageRevision
	}
	return 0
}

type AuditCursorBehindFloor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requested     *AuditCursor           `protobuf:"bytes,1,opt,name=requested,proto3" json:"requested,omitempty"`
	Bounds        *AuditBounds           `protobuf:"bytes,2,opt,name=bounds,proto3" json:"bounds,omitempty"`
	Coverage      *AuditCoverageSnapshot `protobuf:"bytes,3,opt,name=coverage,proto3" json:"coverage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditCursorBehindFloor) Reset() {
	*x = AuditCursorBehindFloor{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditCursorBehindFloor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditCursorBehindFloor) ProtoMessage() {}

func (x *AuditCursorBehindFloor) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditCursorBehindFloor.ProtoReflect.Descriptor instead.
func (*AuditCursorBehindFloor) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{27}
}

func (x *AuditCursorBehindFloor) GetRequested() *AuditCursor {
	if x != nil {
		return x.Requested
	}
	return nil
}

func (x *AuditCursorBehindFloor) GetBounds() *AuditBounds {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *AuditCursorBehindFloor) GetCoverage() *AuditCoverageSnapshot {
	if x != nil {
		return x.Coverage
	}
	return nil
}

type AuditUpstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AuditUpstream_Record
	//	*AuditUpstream_Coverage
	//	*AuditUpstream_CursorBehindFloor
	//	*AuditUpstream_AckResult
	Message       isAuditUpstream_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditUpstream) Reset() {
	*x = AuditUpstream{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditUpstream) ProtoMessage() {}

func (x *AuditUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditUpstream.ProtoReflect.Descriptor instead.
func (*AuditUpstream) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{28}
}

func (x *AuditUpstream) GetMessage() isAuditUpstream_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AuditUpstream) GetRecord() *AuditRecord {
	if x != nil {
		if x, ok := x.Message.(*AuditUpstream_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *AuditUpstream) GetCoverage() *AuditCoverageSnapshot {
	if x != nil {
		if x, ok := x.Message.(*AuditUpstream_Coverage); ok {
			return x.Coverage
		}
	}
	return nil
}

func (x *AuditUpstream) GetCursorBehindFloor() *AuditCursorBehindFloor {
	if x != nil {
		if x, ok := x.Message.(*AuditUpstream_CursorBehindFloor); ok {
			return x.CursorBehindFloor
		}
	}
	return nil
}

func (x *AuditUpstream) GetAckResult() *AuditAckResult {
	if x != nil {
		if x, ok := x.Message.(*AuditUpstream_AckResult); ok {
			return x.AckResult
		}
	}
	return nil
}

type isAuditUpstream_Message interface {
	isAuditUpstream_Message()
}

type AuditUpstream_Record struct {
	Record *AuditRecord `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

type AuditUpstream_Coverage struct {
	Coverage *AuditCoverageSnapshot `protobuf:"bytes,2,opt,name=coverage,proto3,oneof"`
}

type AuditUpstream_CursorBehindFloor struct {
	CursorBehindFloor *AuditCursorBehindFloor `protobuf:"bytes,3,opt,name=cursor_behind_floor,json=cursorBehindFloor,proto3,oneof"`
}

type AuditUpstream_AckResult struct {
	AckResult *AuditAckResult `protobuf:"bytes,4,opt,name=ack_result,json=ackResult,proto3,oneof"`
}

func (*AuditUpstream_Record) isAuditUpstream_Message() {}

func (*AuditUpstream_Coverage) isAuditUpstream_Message() {}

func (*AuditUpstream_CursorBehindFloor) isAuditUpstream_Message() {}

func (*AuditUpstream_AckResult) isAuditUpstream_Message() {}

// AuditArchiveDescriptor names the Server's current Audit Archive. It is sent
// once, downstream, before any acknowledgement, so the Agent can apply the
// archive judgement of architecture 6.4 before it streams any record. A
// protocol N-1 Server never sends one and the Agent then keeps its binding.
type AuditArchiveDescriptor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerIdentityId string                 `protobuf:"bytes,1,opt,name=server_identity_id,json=serverIdentityId,proto3" json:"server_identity_id,omitempty"`
	Generation       uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	AuditArchiveId   string                 `protobuf:"bytes,3,opt,name=audit_archive_id,json=auditArchiveId,proto3" json:"audit_archive_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditArchiveDescriptor) Reset() {
	*x = AuditArchiveDescriptor{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditArchiveDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditArchiveDescriptor) ProtoMessage() {}

func (x *AuditArchiveDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditArchiveDescriptor.ProtoReflect.Descriptor instead.
func (*AuditArchiveDescriptor) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{29}
}

func (x *AuditArchiveDescriptor) GetServerIdentityId() string {
	if x != nil {
		return x.ServerIdentityId
	}
	return ""
}

func (x *AuditArchiveDescriptor) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *AuditArchiveDescriptor) GetAuditArchiveId() string {
	if x != nil {
		return x.AuditArchiveId
	}
	return ""
}

type AuditAck struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AuditArchiveId       string                 `protobuf:"bytes,1,opt,name=audit_archive_id,json=auditArchiveId,proto3" json:"audit_archive_id,omitempty"`
	Cursor               *AuditCursor           `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	CoverageRevisionSeen uint64                 `protobuf:"varint,3,opt,name=coverage_revision_seen,json=coverageRevisionSeen,proto3" json:"coverage_revision_seen,omitempty"`
	// An AuditAck carrying an archive and no cursor is the archive announcement,
	// not an acknowledgement.
	Archive       *AuditArchiveDescriptor `protobuf:"bytes,4,opt,name=archive,proto3" json:"archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAck) Reset() {
	*x = AuditAck{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAck) ProtoMessage() {}

func (x *AuditAck) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAck.ProtoReflect.Descriptor instead.
func (*AuditAck) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{30}
}

func (x *AuditAck) GetAuditArchiveId() string {
	if x != nil {
		return x.AuditArchiveId
	}
	return ""
}

func (x *AuditAck) GetCursor() *AuditCursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *AuditAck) GetCoverageRevisionSeen() uint64 {
	if x != nil {
		return x.CoverageRevisionSeen
	}
	return 0
}

func (x *AuditAck) GetArchive() *AuditArchiveDescriptor {
	if x != nil {
		return x.Archive
	}
	return nil
}

type AuditAckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposed      *AuditCursor           `protobuf:"bytes,1,opt,name=proposed,proto3" json:"proposed,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	StaleCoverage *AuditCoverageSnapshot `protobuf:"bytes,3,opt,name=stale_coverage,json=staleCoverage,proto3" json:"stale_coverage,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAckResult) Reset() {
	*x = AuditAckResult{}
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAckResult) ProtoMessage() {}

func (x *AuditAckResult) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_product_v1_session_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAckResult.ProtoReflect.Descriptor instead.
func (*AuditAckResult) Descriptor() ([]byte, []int) {
	return file_dockpilot_product_v1_session_proto_rawDescGZIP(), []int{31}
}

func (x *AuditAckResult) GetProposed() *AuditCursor {
	if x != nil {
		return x.Proposed
	}
	return nil
}

func (x *AuditAckResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AuditAckResult) GetStaleCoverage() *AuditCoverageSnapshot {
	if x != nil {
		return x.StaleCoverage
	}
	return nil
}

func (x *AuditAckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_dockpilot_product_v1_session_proto protoreflect.FileDescriptor

const file_dockpilot_product_v1_session_proto_rawDesc = "" +
	"\n" +
	"\"dockpilot/product/v1/session.proto\x12\x14dockpilot.product.v1\"=\n" +
	"\x10HeartbeatRequest\x12)\n" +
	"\x11sent_at_unix_nano\x18\x01 \x01(\x03R\x0esentAtUnixNano\"\xa6\x03\n" +
	"\n" +
	"Capability\x12)\n" +
	"\x10connection_ready\x18\x01 \x01(\bR\x0fconnectionReady\x12!\n" +
	"\fdocker_ready\x18\x02 \x01(\bR\vdockerReady\x12#\n" +
	"\rcompose_ready\x18\x03 \x01(\bR\fcomposeReady\x12,\n" +
	"\x12docker_api_version\x18\x04 \x01(\tR\x10dockerApiVersion\x126\n" +
	"\x17bundled_compose_version\x18\x05 \x01(\tR\x15bundledComposeVersion\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x17\n" +
	"\afs_read\x18\a \x01(\bR\x06fsRead\x12\x19\n" +
	"\bfs_write\x18\b \x01(\bR\afsWrite\x12$\n" +
	"\x0efs_read_reason\x18\t \x01(\tR\ffsReadReason\x12&\n" +
	"\x0ffs_write_reason\x18\n" +
	" \x01(\tR\rfsWriteReason\x12%\n" +
	"\x0emetrics_matrix\x18\v \x01(\bR\rmetricsMatrix\"\x88\x01\n" +
	"\x11HeartbeatResponse\x121\n" +
	"\x15observed_at_unix_nano\x18\x01 \x01(\x03R\x12observedAtUnixNano\x12@\n" +
	"\n" +
	"capability\x18\x02 \x01(\v2 .dockpilot.product.v1.CapabilityR\n" +
	"capability\"T\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\")\n" +
	"\rQueryResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x9c\x01\n" +
	"\x10OperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vproject_key\x18\x03 \x01(\tR\n" +
	"projectKey\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\x85\x04\n" +
	"\x11OperationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x128\n" +
	"\x18partial_effects_possible\x18\x04 \x01(\bR\x16partialEffectsPossible\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\voutput_tail\x18\x06 \x01(\fR\n" +
	"outputTail\x12)\n" +
	"\x10output_truncated\x18\a \x01(\bR\x0foutputTruncated\x12\x1f\n" +
	"\vcancel_mode\x18\b \x01(\tR\n" +
	"cancelMode\x12\x1d\n" +
	"\n" +
	"can_cancel\x18\t \x01(\bR\tcanCancel\x121\n" +
	"\x14cancelability_reason\x18\n" +
	" \x01(\tR\x13cancelabilityReason\x123\n" +
	"\x16requested_at_unix_nano\x18\v \x01(\x03R\x13requestedAtUnixNano\x12/\n" +
	"\x14started_at_unix_nano\x18\f \x01(\x03R\x11startedAtUnixNano\x121\n" +
	"\x15finished_at_unix_nano\x18\r \x01(\x03R\x12finishedAtUnixNano\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"s\n" +
	"\x14GetOperationResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12E\n" +
	"\toperation\x18\x02 \x01(\v2'.dockpilot.product.v1.OperationResponseR\toperation\"S\n" +
	"\x16CancelOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"z\n" +
	"\x17CancelOperationResponse\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\x12E\n" +
	"\toperation\x18\x02 \x01(\v2'.dockpilot.product.v1.OperationResponseR\toperation\"\x1d\n" +
	"\x1bListActiveOperationsRequest\"\xc8\x01\n" +
	"\x0fActiveOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vproject_key\x18\x03 \x01(\tR\n" +
	"projectKey\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12E\n" +
	"\toperation\x18\x05 \x01(\v2'.dockpilot.product.v1.OperationResponseR\toperation\"e\n" +
	"\x1cListActiveOperationsResponse\x12E\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2%.dockpilot.product.v1.ActiveOperationR\n" +
	"operations\"\xb7\x02\n" +
	"\x10LogStreamRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x04R\ttailLines\x12\x1f\n" +
	"\vshow_stdout\x18\x04 \x01(\bR\n" +
	"showStdout\x12\x1f\n" +
	"\vshow_stderr\x18\x05 \x01(\bR\n" +
	"showStderr\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x06 \x01(\bR\n" +
	"timestamps\x12\x1f\n" +
	"\vproject_uid\x18\a \x01(\tR\n" +
	"projectUid\x12\x1a\n" +
	"\bservices\x18\b \x03(\tR\bservices\x12\x14\n" +
	"\x05since\x18\t \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\n" +
	" \x01(\tR\x05until\"\x81\x02\n" +
	"\bLogEvent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x1d\n" +
	"\n" +
	"line_count\x18\x03 \x01(\x04R\tlineCount\x12.\n" +
	"\x13timestamp_unix_nano\x18\x04 \x01(\x03R\x11timestampUnixNano\x12#\n" +
	"\rdropped_bytes\x18\x05 \x01(\x04R\fdroppedBytes\x12#\n" +
	"\rdropped_lines\x18\x06 \x01(\x04R\fdroppedLines\x12\x1a\n" +
	"\bterminal\x18\a \x01(\bR\bterminal\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"7\n" +
	"\x12StatsStreamRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\x16\n" +
	"\x14MetricsMatrixRequest\"\xa1\x01\n" +
	"\x11ManagedFilesystem\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x03 \x01(\x04R\tfreeBytes\x12 \n" +
	"\vunavailable\x18\x04 \x01(\bR\vunavailable\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x82\x02\n" +
	"\x0fWorkloadSummary\x12!\n" +
	"\fcpu_capacity\x18\x01 \x01(\rR\vcpuCapacity\x12'\n" +
	"\x0fmemory_capacity\x18\x02 \x01(\x04R\x0ememoryCapacity\x12-\n" +
	"\x12containers_running\x18\x03 \x01(\rR\x11containersRunning\x12)\n" +
	"\x10containers_total\x18\x04 \x01(\rR\x0fcontainersTotal\x12I\n" +
	"\vfilesystems\x18\x05 \x03(\v2'.dockpilot.product.v1.ManagedFilesystemR\vfilesystems\"\xd0\x03\n" +
	"\x12MetricsMatrixFrame\x121\n" +
	"\x15observed_at_unix_nano\x18\x01 \x01(\x03R\x12observedAtUnixNano\x12A\n" +
	"\bworkload\x18\x02 \x01(\v2%.dockpilot.product.v1.WorkloadSummaryR\bworkload\x12A\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2!.dockpilot.product.v1.StatsSampleR\n" +
	"containers\x12%\n" +
	"\x0edropped_frames\x18\x04 \x01(\x04R\rdroppedFrames\x12)\n" +
	"\x10membership_stale\x18\x05 \x01(\bR\x0fmembershipStale\x12+\n" +
	"\x11membership_reason\x18\x06 \x01(\tR\x10membershipReason\x122\n" +
	"\x15pending_container_ids\x18\a \x03(\tR\x13pendingContainerIds\x12%\n" +
	"\x0eworkload_stale\x18\b \x01(\bR\rworkloadStale\x12'\n" +
	"\x0fworkload_reason\x18\t \x01(\tR\x0eworkloadReason\"\xa6\x03\n" +
	"\vStatsSample\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x121\n" +
	"\x15observed_at_unix_nano\x18\x02 \x01(\x03R\x12observedAtUnixNano\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x04R\vmemoryUsage\x12!\n" +
	"\fmemory_limit\x18\x05 \x01(\x04R\vmemoryLimit\x12\x1d\n" +
	"\n" +
	"network_rx\x18\x06 \x01(\x04R\tnetworkRx\x12\x1d\n" +
	"\n" +
	"network_tx\x18\a \x01(\x04R\tnetworkTx\x12\x1d\n" +
	"\n" +
	"block_read\x18\b \x01(\x04R\tblockRead\x12\x1f\n" +
	"\vblock_write\x18\t \x01(\x04R\n" +
	"blockWrite\x12#\n" +
	"\rrestart_count\x18\n" +
	" \x01(\x04R\frestartCount\x12\x16\n" +
	"\x06health\x18\v \x01(\tR\x06health\x12\x1f\n" +
	"\vuptime_nano\x18\f \x01(\x03R\n" +
	"uptimeNano\"K\n" +
	"\vAuditCursor\x12 \n" +
	"\vincarnation\x18\x01 \x01(\x04R\vincarnation\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"\x95\x01\n" +
	"\vAuditRecord\x129\n" +
	"\x06cursor\x18\x01 \x01(\v2!.dockpilot.product.v1.AuditCursorR\x06cursor\x121\n" +
	"\x15appended_at_unix_nano\x18\x02 \x01(\x03R\x12appendedAtUnixNano\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xdc\x01\n" +
	"\bAuditGap\x12 \n" +
	"\vincarnation\x18\x01 \x01(\x04R\vincarnation\x12#\n" +
	"\rfrom_sequence\x18\x02 \x01(\x04R\ffromSequence\x12%\n" +
	"\x0euntil_sequence\x18\x03 \x01(\x04R\runtilSequence\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1c\n" +
	"\tprecision\x18\x05 \x01(\tR\tprecision\x12,\n" +
	"\x12last_loss_revision\x18\x06 \x01(\x04R\x10lastLossRevision\"\xe0\x01\n" +
	"\x15AuditCoverageSnapshot\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x123\n" +
	"\x16generated_at_unix_nano\x18\x02 \x01(\x03R\x13generatedAtUnixNano\x122\n" +
	"\x04gaps\x18\x03 \x03(\v2\x1e.dockpilot.product.v1.AuditGapR\x04gaps\x12B\n" +
	"\x1dcoverage_unknown_incarnations\x18\x04 \x03(\x04R\x1bcoverageUnknownIncarnations\"\x8f\x03\n" +
	"\vAuditBounds\x12>\n" +
	"\twal_floor\x18\x01 \x01(\v2!.dockpilot.product.v1.AuditCursorR\bwalFloor\x12B\n" +
	"\vwal_ceiling\x18\x02 \x01(\v2!.dockpilot.product.v1.AuditCursorR\n" +
	"walCeiling\x12B\n" +
	"\vnext_cursor\x18\x03 \x01(\v2!.dockpilot.product.v1.AuditCursorR\n" +
	"nextCursor\x12S\n" +
	"\x14server_acked_through\x18\x04 \x01(\v2!.dockpilot.product.v1.AuditCursorR\x12serverAckedThrough\x126\n" +
	"\x17acknowledged_archive_id\x18\x05 \x01(\tR\x15acknowledgedArchiveId\x12+\n" +
	"\x11coverage_revision\x18\x06 \x01(\x04R\x10coverageRevision\"\xdd\x01\n" +
	"\x16AuditCursorBehindFloor\x12?\n" +
	"\trequested\x18\x01 \x01(\v2!.dockpilot.product.v1.AuditCursorR\trequested\x129\n" +
	"\x06bounds\x18\x02 \x01(\v2!.dockpilot.product.v1.AuditBoundsR\x06bounds\x12G\n" +
	"\bcoverage\x18\x03 \x01(\v2+.dockpilot.product.v1.AuditCoverageSnapshotR\bcoverage\"\xc9\x02\n" +
	"\rAuditUpstream\x12;\n" +
	"\x06record\x18\x01 \x01(\v2!.dockpilot.product.v1.AuditRecordH\x00R\x06record\x12I\n" +
	"\bcoverage\x18\x02 \x01(\v2+.dockpilot.product.v1.AuditCoverageSnapshotH\x00R\bcoverage\x12^\n" +
	"\x13cursor_behind_floor\x18\x03 \x01(\v2,.dockpilot.product.v1.AuditCursorBehindFloorH\x00R\x11cursorBehindFloor\x12E\n" +
	"\n" +
	"ack_result\x18\x04 \x01(\v2$.dockpilot.product.v1.AuditAckResultH\x00R\tackResultB\t\n" +
	"\amessage\"\x90\x01\n" +
	"\x16AuditArchiveDescriptor\x12,\n" +
	"\x12server_identity_id\x18\x01 \x01(\tR\x10serverIdentityId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12(\n" +
	"\x10audit_archive_id\x18\x03 \x01(\tR\x0eauditArchiveId\"\xed\x01\n" +
	"\bAuditAck\x12(\n" +
	"\x10audit_archive_id\x18\x01 \x01(\tR\x0eauditArchiveId\x129\n" +
	"\x06cursor\x18\x02 \x01(\v2!.dockpilot.product.v1.AuditCursorR\x06cursor\x124\n" +
	"\x16coverage_revision_seen\x18\x03 \x01(\x04R\x14coverageRevisionSeen\x12F\n" +
	"\aarchive\x18\x04 \x01(\v2,.dockpilot.product.v1.AuditArchiveDescriptorR\aarchive\"\xd5\x01\n" +
	"\x0eAuditAckResult\x12=\n" +
	"\bproposed\x18\x01 \x01(\v2!.dockpilot.product.v1.AuditCursorR\bproposed\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12R\n" +
	"\x0estale_coverage\x18\x03 \x01(\v2+.dockpilot.product.v1.AuditCoverageSnapshotR\rstaleCoverage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB@Z>github.com/east-true/dockpilot/internal/producttransport/pb;pbb\x06proto3"

var (
	file_dockpilot_product_v1_session_proto_rawDescOnce sync.Once
	file_dockpilot_product_v1_session_proto_rawDescData []byte
)

func file_dockpilot_product_v1_session_proto_rawDescGZIP() []byte {
	file_dockpilot_product_v1_session_proto_rawDescOnce.Do(func() {
		file_dockpilot_product_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dockpilot_product_v1_session_proto_rawDesc), len(file_dockpilot_product_v1_session_proto_rawDesc)))
	})
	return file_dockpilot_product_v1_session_proto_rawDescData
}

var file_dockpilot_product_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_dockpilot_product_v1_session_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),             // 0: dockpilot.product.v1.HeartbeatRequest
	(*Capability)(nil),                   // 1: dockpilot.product.v1.Capability
	(*HeartbeatResponse)(nil),            // 2: dockpilot.product.v1.HeartbeatResponse
	(*QueryRequest)(nil),                 // 3: dockpilot.product.v1.QueryRequest
	(*QueryResponse)(nil),                // 4: dockpilot.product.v1.QueryResponse
	(*OperationRequest)(nil),             // 5: dockpilot.product.v1.OperationRequest
	(*OperationResponse)(nil),            // 6: dockpilot.product.v1.OperationResponse
	(*GetOperationRequest)(nil),          // 7: dockpilot.product.v1.GetOperationRequest
	(*GetOperationResponse)(nil),         // 8: dockpilot.product.v1.GetOperationResponse
	(*CancelOperationRequest)(nil),       // 9: dockpilot.product.v1.CancelOperationRequest
	(*CancelOperationResponse)(nil),      // 10: dockpilot.product.v1.CancelOperationResponse
	(*ListActiveOperationsRequest)(nil),  // 11: dockpilot.product.v1.ListActiveOperationsRequest
	(*ActiveOperation)(nil),              // 12: dockpilot.product.v1.ActiveOperation
	(*ListActiveOperationsResponse)(nil), // 13: dockpilot.product.v1.ListActiveOperationsResponse
	(*LogStreamRequest)(nil),             // 14: dockpilot.product.v1.LogStreamRequest
	(*LogEvent)(nil),                     // 15: dockpilot.product.v1.LogEvent
	(*StatsStreamRequest)(nil),           // 16: dockpilot.product.v1.StatsStreamRequest
	(*MetricsMatrixRequest)(nil),         // 17: dockpilot.product.v1.MetricsMatrixRequest
	(*ManagedFilesystem)(nil),            // 18: dockpilot.product.v1.ManagedFilesystem
	(*WorkloadSummary)(nil),              // 19: dockpilot.product.v1.WorkloadSummary
	(*MetricsMatrixFrame)(nil),           // 20: dockpilot.product.v1.MetricsMatrixFrame
	(*StatsSample)(nil),                  // 21: dockpilot.product.v1.StatsSample
	(*AuditCursor)(nil),                  // 22: dockpilot.product.v1.AuditCursor
	(*AuditRecord)(nil),                  // 23: dockpilot.product.v1.AuditRecord
	(*AuditGap)(nil),                     // 24: dockpilot.product.v1.AuditGap
	(*AuditCoverageSnapshot)(nil),        // 25: dockpilot.product.v1.AuditCoverageSnapshot
	(*AuditBounds)(nil),                  // 26: dockpilot.product.v1.AuditBounds
	(*AuditCursorBehindFloor)(nil),       // 27: dockpilot.product.v1.AuditCursorBehindFloor
	(*AuditUpstream)(nil),                // 28: dockpilot.product.v1.AuditUpstream
	(*AuditArchiveDescriptor)(nil),       // 29: dockpilot.product.v1.AuditArchiveDescriptor
	(*AuditAck)(nil),                     // 30: dockpilot.product.v1.AuditAck
	(*AuditAckResult)(nil),               // 31: dockpilot.product.v1.AuditAckResult
}
var file_dockpilot_product_v1_session_proto_depIdxs = []int32{
	1,  // 0: dockpilot.product.v1.HeartbeatResponse.capability:type_name -> dockpilot.product.v1.Capability
	6,  // 1: dockpilot.product.v1.GetOperationResponse.operation:type_name -> dockpilot.product.v1.OperationResponse
	6,  // 2: dockpilot.product.v1.CancelOperationResponse.operation:type_name -> dockpilot.product.v1.OperationResponse
	6,  // 3: dockpilot.product.v1.ActiveOperation.operation:type_name -> dockpilot.product.v1.OperationResponse
	12, // 4: dockpilot.product.v1.ListActiveOperationsResponse.operations:type_name -> dockpilot.product.v1.ActiveOperation
	18, // 5: dockpilot.product.v1.WorkloadSummary.filesystems:type_name -> dockpilot.product.v1.ManagedFilesystem
	19, // 6: dockpilot.product.v1.MetricsMatrixFrame.workload:type_name -> dockpilot.product.v1.WorkloadSummary
	21, // 7: dockpilot.product.v1.MetricsMatrixFrame.containers:type_name -> dockpilot.product.v1.StatsSample
	22, // 8: dockpilot.product.v1.AuditRecord.cursor:type_name -> dockpilot.product.v1.AuditCursor
	24, // 9: dockpilot.product.v1.AuditCoverageSnapshot.gaps:type_name -> dockpilot.product.v1.AuditGap
	22, // 10: dockpilot.product.v1.AuditBounds.wal_floor:type_name -> dockpilot.product.v1.AuditCursor
	22, // 11: dockpilot.product.v1.AuditBounds.wal_ceiling:type_name -> dockpilot.product.v1.AuditCursor
	22, // 12: dockpilot.product.v1.AuditBounds.next_cursor:type_name -> dockpilot.product.v1.AuditCursor
	22, // 13: dockpilot.product.v1.AuditBounds.server_acked_through:type_name -> dockpilot.product.v1.AuditCursor
	22, // 14: dockpilot.product.v1.AuditCursorBehindFloor.requested:type_name -> dockpilot.product.v1.AuditCursor
	26, // 15: dockpilot.product.v1.AuditCursorBehindFloor.bounds:type_name -> dockpilot.product.v1.AuditBounds
	25, // 16: dockpilot.product.v1.AuditCursorBehindFloor.coverage:type_name -> dockpilot.product.v1.AuditCoverageSnapshot
	23, // 17: dockpilot.product.v1.AuditUpstream.record:type_name -> dockpilot.product.v1.AuditRecord
	25, // 18: dockpilot.product.v1.AuditUpstream.coverage:type_name -> dockpilot.product.v1.AuditCoverageSnapshot
	27, // 19: dockpilot.product.v1.AuditUpstream.cursor_behind_floor:type_name -> dockpilot.product.v1.AuditCursorBehindFloor
	31, // 20: dockpilot.product.v1.AuditUpstream.ack_result:type_name -> dockpilot.product.v1.AuditAckResult
	22, // 21: dockpilot.product.v1.AuditAck.cursor:type_name -> dockpilot.product.v1.AuditCursor
	29, // 22: dockpilot.product.v1.AuditAck.archive:type_name -> dockpilot.product.v1.AuditArchiveDescriptor
	22, // 23: dockpilot.product.v1.AuditAckResult.proposed:type_name -> dockpilot.product.v1.AuditCursor
	25, // 24: dockpilot.product.v1.AuditAckResult.stale_coverage:type_name -> dockpilot.product.v1.AuditCoverageSnapshot
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_dockpilot_product_v1_session_proto_init() }
func file_dockpilot_product_v1_session_proto_init() {
	if File_dockpilot_product_v1_session_proto != nil {
		return
	}
	file_dockpilot_product_v1_session_proto_msgTypes[28].OneofWrappers = []any{
		(*AuditUpstream_Record)(nil),
		(*AuditUpstream_Coverage)(nil),
		(*AuditUpstream_CursorBehindFloor)(nil),
		(*AuditUpstream_AckResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dockpilot_product_v1_session_proto_rawDesc), len(file_dockpilot_product_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dockpilot_product_v1_session_proto_goTypes,
		DependencyIndexes: file_dockpilot_product_v1_session_proto_depIdxs,
		MessageInfos:      file_dockpilot_product_v1_session_proto_msgTypes,
	}.Build()
	File_dockpilot_product_v1_session_proto = out.File
	file_dockpilot_product_v1_session_proto_goTypes = nil
	file_dockpilot_product_v1_session_proto_depIdxs = nil
}
