// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: docklattice/prototype/v1/contract.proto

// docklattice.prototype.v1은 Transport Prototype(부록 A)의 논리 페이로드
// 정의다. 두 후보는 동일한 직렬화 형식을 쓴다(부록 A.7 통제 변수).
//
// 이 파일에는 전송 기술에 종속된 것이 들어가지 않는다. gRPC service 정의는
// 후보 A adapter 안에만 존재한다.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CancelReason int32

const (
	CancelReason_CANCEL_REASON_UNSPECIFIED    CancelReason = 0
	CancelReason_CANCEL_REASON_USER           CancelReason = 1
	CancelReason_CANCEL_REASON_TIMEOUT        CancelReason = 2
	CancelReason_CANCEL_REASON_AGENT_SHUTDOWN CancelReason = 3
)

// Enum value maps for CancelReason.
var (
	CancelReason_name = map[int32]string{
		0: "CANCEL_REASON_UNSPECIFIED",
		1: "CANCEL_REASON_USER",
		2: "CANCEL_REASON_TIMEOUT",
		3: "CANCEL_REASON_AGENT_SHUTDOWN",
	}
	CancelReason_value = map[string]int32{
		"CANCEL_REASON_UNSPECIFIED":    0,
		"CANCEL_REASON_USER":           1,
		"CANCEL_REASON_TIMEOUT":        2,
		"CANCEL_REASON_AGENT_SHUTDOWN": 3,
	}
)

func (x CancelReason) Enum() *CancelReason {
	p := new(CancelReason)
	*p = x
	return p
}

func (x CancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_docklattice_prototype_v1_contract_proto_enumTypes[0].Descriptor()
}

func (CancelReason) Type() protoreflect.EnumType {
	return &file_docklattice_prototype_v1_contract_proto_enumTypes[0]
}

func (x CancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelReason.Descriptor instead.
func (CancelReason) EnumDescriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{0}
}

// ADR §9.4의 응답 집합이다.
type CancelResult int32

const (
	CancelResult_CANCEL_RESULT_UNSPECIFIED      CancelResult = 0
	CancelResult_CANCEL_RESULT_ACCEPTED         CancelResult = 1
	CancelResult_CANCEL_RESULT_TOO_LATE         CancelResult = 2
	CancelResult_CANCEL_RESULT_NOT_CANCELABLE   CancelResult = 3
	CancelResult_CANCEL_RESULT_ALREADY_TERMINAL CancelResult = 4
	CancelResult_CANCEL_RESULT_NOT_FOUND        CancelResult = 5
)

// Enum value maps for CancelResult.
var (
	CancelResult_name = map[int32]string{
		0: "CANCEL_RESULT_UNSPECIFIED",
		1: "CANCEL_RESULT_ACCEPTED",
		2: "CANCEL_RESULT_TOO_LATE",
		3: "CANCEL_RESULT_NOT_CANCELABLE",
		4: "CANCEL_RESULT_ALREADY_TERMINAL",
		5: "CANCEL_RESULT_NOT_FOUND",
	}
	CancelResult_value = map[string]int32{
		"CANCEL_RESULT_UNSPECIFIED":      0,
		"CANCEL_RESULT_ACCEPTED":         1,
		"CANCEL_RESULT_TOO_LATE":         2,
		"CANCEL_RESULT_NOT_CANCELABLE":   3,
		"CANCEL_RESULT_ALREADY_TERMINAL": 4,
		"CANCEL_RESULT_NOT_FOUND":        5,
	}
)

func (x CancelResult) Enum() *CancelResult {
	p := new(CancelResult)
	*p = x
	return p
}

func (x CancelResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelResult) Descriptor() protoreflect.EnumDescriptor {
	return file_docklattice_prototype_v1_contract_proto_enumTypes[1].Descriptor()
}

func (CancelResult) Type() protoreflect.EnumType {
	return &file_docklattice_prototype_v1_contract_proto_enumTypes[1]
}

func (x CancelResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelResult.Descriptor instead.
func (CancelResult) EnumDescriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{1}
}

// ADR §8.6의 phase다.
type OperationPhase int32

const (
	OperationPhase_OPERATION_PHASE_UNSPECIFIED OperationPhase = 0
	OperationPhase_OPERATION_PHASE_PREPARING   OperationPhase = 1
	OperationPhase_OPERATION_PHASE_EXECUTING   OperationPhase = 2
	OperationPhase_OPERATION_PHASE_COMMITTING  OperationPhase = 3
	OperationPhase_OPERATION_PHASE_FINALIZING  OperationPhase = 4
	OperationPhase_OPERATION_PHASE_TERMINAL    OperationPhase = 5
)

// Enum value maps for OperationPhase.
var (
	OperationPhase_name = map[int32]string{
		0: "OPERATION_PHASE_UNSPECIFIED",
		1: "OPERATION_PHASE_PREPARING",
		2: "OPERATION_PHASE_EXECUTING",
		3: "OPERATION_PHASE_COMMITTING",
		4: "OPERATION_PHASE_FINALIZING",
		5: "OPERATION_PHASE_TERMINAL",
	}
	OperationPhase_value = map[string]int32{
		"OPERATION_PHASE_UNSPECIFIED": 0,
		"OPERATION_PHASE_PREPARING":   1,
		"OPERATION_PHASE_EXECUTING":   2,
		"OPERATION_PHASE_COMMITTING":  3,
		"OPERATION_PHASE_FINALIZING":  4,
		"OPERATION_PHASE_TERMINAL":    5,
	}
)

func (x OperationPhase) Enum() *OperationPhase {
	p := new(OperationPhase)
	*p = x
	return p
}

func (x OperationPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_docklattice_prototype_v1_contract_proto_enumTypes[2].Descriptor()
}

func (OperationPhase) Type() protoreflect.EnumType {
	return &file_docklattice_prototype_v1_contract_proto_enumTypes[2]
}

func (x OperationPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationPhase.Descriptor instead.
func (OperationPhase) EnumDescriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{2}
}

// ADR §9.2의 cancel mode다.
type CancelMode int32

const (
	CancelMode_CANCEL_MODE_UNSPECIFIED         CancelMode = 0
	CancelMode_CANCEL_MODE_SAFE                CancelMode = 1
	CancelMode_CANCEL_MODE_BEST_EFFORT_PARTIAL CancelMode = 2
	CancelMode_CANCEL_MODE_BEFORE_COMMIT       CancelMode = 3
)

// Enum value maps for CancelMode.
var (
	CancelMode_name = map[int32]string{
		0: "CANCEL_MODE_UNSPECIFIED",
		1: "CANCEL_MODE_SAFE",
		2: "CANCEL_MODE_BEST_EFFORT_PARTIAL",
		3: "CANCEL_MODE_BEFORE_COMMIT",
	}
	CancelMode_value = map[string]int32{
		"CANCEL_MODE_UNSPECIFIED":         0,
		"CANCEL_MODE_SAFE":                1,
		"CANCEL_MODE_BEST_EFFORT_PARTIAL": 2,
		"CANCEL_MODE_BEFORE_COMMIT":       3,
	}
)

func (x CancelMode) Enum() *CancelMode {
	p := new(CancelMode)
	*p = x
	return p
}

func (x CancelMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelMode) Descriptor() protoreflect.EnumDescriptor {
	return file_docklattice_prototype_v1_contract_proto_enumTypes[3].Descriptor()
}

func (CancelMode) Type() protoreflect.EnumType {
	return &file_docklattice_prototype_v1_contract_proto_enumTypes[3]
}

func (x CancelMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelMode.Descriptor instead.
func (CancelMode) EnumDescriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{3}
}

type GapReason int32

const (
	GapReason_GAP_REASON_UNSPECIFIED   GapReason = 0
	GapReason_GAP_REASON_RETENTION     GapReason = 1
	GapReason_GAP_REASON_DISK_PRESSURE GapReason = 2
)

// Enum value maps for GapReason.
var (
	GapReason_name = map[int32]string{
		0: "GAP_REASON_UNSPECIFIED",
		1: "GAP_REASON_RETENTION",
		2: "GAP_REASON_DISK_PRESSURE",
	}
	GapReason_value = map[string]int32{
		"GAP_REASON_UNSPECIFIED":   0,
		"GAP_REASON_RETENTION":     1,
		"GAP_REASON_DISK_PRESSURE": 2,
	}
)

func (x GapReason) Enum() *GapReason {
	p := new(GapReason)
	*p = x
	return p
}

func (x GapReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GapReason) Descriptor() protoreflect.EnumDescriptor {
	return file_docklattice_prototype_v1_contract_proto_enumTypes[4].Descriptor()
}

func (GapReason) Type() protoreflect.EnumType {
	return &file_docklattice_prototype_v1_contract_proto_enumTypes[4]
}

func (x GapReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GapReason.Descriptor instead.
func (GapReason) EnumDescriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{4}
}

type Precision int32

const (
	Precision_PRECISION_UNSPECIFIED Precision = 0
	Precision_PRECISION_EXACT       Precision = 1
	Precision_PRECISION_COALESCED   Precision = 2
)

// Enum value maps for Precision.
var (
	Precision_name = map[int32]string{
		0: "PRECISION_UNSPECIFIED",
		1: "PRECISION_EXACT",
		2: "PRECISION_COALESCED",
	}
	Precision_value = map[string]int32{
		"PRECISION_UNSPECIFIED": 0,
		"PRECISION_EXACT":       1,
		"PRECISION_COALESCED":   2,
	}
)

func (x Precision) Enum() *Precision {
	p := new(Precision)
	*p = x
	return p
}

func (x Precision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Precision) Descriptor() protoreflect.EnumDescriptor {
	return file_docklattice_prototype_v1_contract_proto_enumTypes[5].Descriptor()
}

func (Precision) Type() protoreflect.EnumType {
	return &file_docklattice_prototype_v1_contract_proto_enumTypes[5]
}

func (x Precision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Precision.Descriptor instead.
func (Precision) EnumDescriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{5}
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type RegisterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capability      *Capability            `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RegisterResponse) GetCapability() *Capability {
	if x != nil {
		return x.Capability
	}
	return nil
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SentAtUnixNano int64                  `protobuf:"varint,1,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SentAtUnixNano int64                  `protobuf:"varint,1,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`
	Capability     *Capability            `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

func (x *HeartbeatResponse) GetCapability() *Capability {
	if x != nil {
		return x.Capability
	}
	return nil
}

// Capability는 연결·Docker·Compose 능력을 분리해 보고한다(ADR §18).
// 프로토타입에서는 값을 고정 보고한다. Docker를 호출하지 않는다(A.5).
type Capability struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FsWrite               bool                   `protobuf:"varint,1,opt,name=fs_write,json=fsWrite,proto3" json:"fs_write,omitempty"`
	ComposeExec           bool                   `protobuf:"varint,2,opt,name=compose_exec,json=composeExec,proto3" json:"compose_exec,omitempty"`
	BundledComposeVersion string                 `protobuf:"bytes,3,opt,name=bundled_compose_version,json=bundledComposeVersion,proto3" json:"bundled_compose_version,omitempty"`
	DockerApiVersion      string                 `protobuf:"bytes,4,opt,name=docker_api_version,json=dockerApiVersion,proto3" json:"docker_api_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{4}
}

func (x *Capability) GetFsWrite() bool {
	if x != nil {
		return x.FsWrite
	}
	return false
}

func (x *Capability) GetComposeExec() bool {
	if x != nil {
		return x.ComposeExec
	}
	return false
}

func (x *Capability) GetBundledComposeVersion() string {
	if x != nil {
		return x.BundledComposeVersion
	}
	return ""
}

func (x *Capability) GetDockerApiVersion() string {
	if x != nil {
		return x.DockerApiVersion
	}
	return ""
}

type CancelOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Reason        CancelReason           `protobuf:"varint,2,opt,name=reason,proto3,enum=docklattice.prototype.v1.CancelReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationRequest.ProtoReflect.Descriptor instead.
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CancelOperationRequest) GetReason() CancelReason {
	if x != nil {
		return x.Reason
	}
	return CancelReason_CANCEL_REASON_UNSPECIFIED
}

type CancelOperationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Result              CancelResult           `protobuf:"varint,1,opt,name=result,proto3,enum=docklattice.prototype.v1.CancelResult" json:"result,omitempty"`
	RequestedAtUnixNano int64                  `protobuf:"varint,2,opt,name=requested_at_unix_nano,json=requestedAtUnixNano,proto3" json:"requested_at_unix_nano,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CancelOperationResponse) Reset() {
	*x = CancelOperationResponse{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationResponse) ProtoMessage() {}

func (x *CancelOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationResponse.ProtoReflect.Descriptor instead.
func (*CancelOperationResponse) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOperationResponse) GetResult() CancelResult {
	if x != nil {
		return x.Result
	}
	return CancelResult_CANCEL_RESULT_UNSPECIFIED
}

func (x *CancelOperationResponse) GetRequestedAtUnixNano() int64 {
	if x != nil {
		return x.RequestedAtUnixNano
	}
	return 0
}

type OperationProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationProgressRequest) Reset() {
	*x = OperationProgressRequest{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationProgressRequest) ProtoMessage() {}

func (x *OperationProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationProgressRequest.ProtoReflect.Descriptor instead.
func (*OperationProgressRequest) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{7}
}

// ADR §8.6: Server는 가장 높은 operation_revision만 반영한다.
type OperationProgressEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OperationId        string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	OperationRevision  uint64                 `protobuf:"varint,2,opt,name=operation_revision,json=operationRevision,proto3" json:"operation_revision,omitempty"`
	Phase              OperationPhase         `protobuf:"varint,3,opt,name=phase,proto3,enum=docklattice.prototype.v1.OperationPhase" json:"phase,omitempty"`
	CancelMode         CancelMode             `protobuf:"varint,4,opt,name=cancel_mode,json=cancelMode,proto3,enum=docklattice.prototype.v1.CancelMode" json:"cancel_mode,omitempty"`
	OccurredAtUnixNano int64                  `protobuf:"varint,5,opt,name=occurred_at_unix_nano,json=occurredAtUnixNano,proto3" json:"occurred_at_unix_nano,omitempty"`
	Detail             string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Terminal           bool                   `protobuf:"varint,7,opt,name=terminal,proto3" json:"terminal,omitempty"`
	TerminalStatus     string                 `protobuf:"bytes,8,opt,name=terminal_status,json=terminalStatus,proto3" json:"terminal_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OperationProgressEvent) Reset() {
	*x = OperationProgressEvent{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationProgressEvent) ProtoMessage() {}

func (x *OperationProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationProgressEvent.ProtoReflect.Descriptor instead.
func (*OperationProgressEvent) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{8}
}

func (x *OperationProgressEvent) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationProgressEvent) GetOperationRevision() uint64 {
	if x != nil {
		return x.OperationRevision
	}
	return 0
}

func (x *OperationProgressEvent) GetPhase() OperationPhase {
	if x != nil {
		return x.Phase
	}
	return OperationPhase_OPERATION_PHASE_UNSPECIFIED
}

func (x *OperationProgressEvent) GetCancelMode() CancelMode {
	if x != nil {
		return x.CancelMode
	}
	return CancelMode_CANCEL_MODE_UNSPECIFIED
}

func (x *OperationProgressEvent) GetOccurredAtUnixNano() int64 {
	if x != nil {
		return x.OccurredAtUnixNano
	}
	return 0
}

func (x *OperationProgressEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *OperationProgressEvent) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *OperationProgressEvent) GetTerminalStatus() string {
	if x != nil {
		return x.TerminalStatus
	}
	return ""
}

// Cursor는 (incarnation, seq) 복합값이다. -1 연산을 정의하지 않는다
// (ADR §11.4). 범위는 half-open [from, until)으로 표현한다.
type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incarnation   uint64                 `protobuf:"varint,1,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{9}
}

func (x *Cursor) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *Cursor) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type AuditRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Incarnation        uint64                 `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Seq                uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	OccurredAtUnixNano int64                  `protobuf:"varint,4,opt,name=occurred_at_unix_nano,json=occurredAtUnixNano,proto3" json:"occurred_at_unix_nano,omitempty"`
	// kind는 managed / observed / continuity_uncertain 등 in-band record 종류다.
	Kind          string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload       []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{10}
}

func (x *AuditRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AuditRecord) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *AuditRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AuditRecord) GetOccurredAtUnixNano() int64 {
	if x != nil {
		return x.OccurredAtUnixNano
	}
	return 0
}

func (x *AuditRecord) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AuditRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SyncAuditMessage는 Agent -> Server 방향 메시지다.
type SyncAuditMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*SyncAuditMessage_Record
	//	*SyncAuditMessage_CoverageChanged
	//	*SyncAuditMessage_AckResult
	Body          isSyncAuditMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAuditMessage) Reset() {
	*x = SyncAuditMessage{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAuditMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAuditMessage) ProtoMessage() {}

func (x *SyncAuditMessage) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAuditMessage.ProtoReflect.Descriptor instead.
func (*SyncAuditMessage) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{11}
}

func (x *SyncAuditMessage) GetBody() isSyncAuditMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SyncAuditMessage) GetRecord() *AuditRecord {
	if x != nil {
		if x, ok := x.Body.(*SyncAuditMessage_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *SyncAuditMessage) GetCoverageChanged() *CoverageChanged {
	if x != nil {
		if x, ok := x.Body.(*SyncAuditMessage_CoverageChanged); ok {
			return x.CoverageChanged
		}
	}
	return nil
}

func (x *SyncAuditMessage) GetAckResult() *AckResult {
	if x != nil {
		if x, ok := x.Body.(*SyncAuditMessage_AckResult); ok {
			return x.AckResult
		}
	}
	return nil
}

type isSyncAuditMessage_Body interface {
	isSyncAuditMessage_Body()
}

type SyncAuditMessage_Record struct {
	Record *AuditRecord `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

type SyncAuditMessage_CoverageChanged struct {
	CoverageChanged *CoverageChanged `protobuf:"bytes,2,opt,name=coverage_changed,json=coverageChanged,proto3,oneof"`
}

type SyncAuditMessage_AckResult struct {
	AckResult *AckResult `protobuf:"bytes,3,opt,name=ack_result,json=ackResult,proto3,oneof"`
}

func (*SyncAuditMessage_Record) isSyncAuditMessage_Body() {}

func (*SyncAuditMessage_CoverageChanged) isSyncAuditMessage_Body() {}

func (*SyncAuditMessage_AckResult) isSyncAuditMessage_Body() {}

// CoverageChanged는 Coverage 변경 알림이다. Server는 이를 받으면 전체
// snapshot을 다시 받는다. Delta Coverage API는 만들지 않는다(ADR §11.7).
type CoverageChanged struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CoverageRevision uint64                 `protobuf:"varint,1,opt,name=coverage_revision,json=coverageRevision,proto3" json:"coverage_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CoverageChanged) Reset() {
	*x = CoverageChanged{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverageChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverageChanged) ProtoMessage() {}

func (x *CoverageChanged) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverageChanged.ProtoReflect.Descriptor instead.
func (*CoverageChanged) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{12}
}

func (x *CoverageChanged) GetCoverageRevision() uint64 {
	if x != nil {
		return x.CoverageRevision
	}
	return 0
}

// SyncAuditAck는 Server -> Agent 방향 메시지다(ADR §11.8).
type SyncAuditAck struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AuditArchiveId       string                 `protobuf:"bytes,1,opt,name=audit_archive_id,json=auditArchiveId,proto3" json:"audit_archive_id,omitempty"`
	Cursor               *Cursor                `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	CoverageRevisionSeen uint64                 `protobuf:"varint,3,opt,name=coverage_revision_seen,json=coverageRevisionSeen,proto3" json:"coverage_revision_seen,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SyncAuditAck) Reset() {
	*x = SyncAuditAck{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAuditAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAuditAck) ProtoMessage() {}

func (x *SyncAuditAck) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAuditAck.ProtoReflect.Descriptor instead.
func (*SyncAuditAck) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{13}
}

func (x *SyncAuditAck) GetAuditArchiveId() string {
	if x != nil {
		return x.AuditArchiveId
	}
	return ""
}

func (x *SyncAuditAck) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *SyncAuditAck) GetCoverageRevisionSeen() uint64 {
	if x != nil {
		return x.CoverageRevisionSeen
	}
	return 0
}

type AckResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// stale_coverage일 때 Agent는 현재 snapshot을 동봉한다(ADR §11.8).
	Snapshot                  *AuditCoverageSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	BlockingRanges            []*CoverageRange       `protobuf:"bytes,3,rep,name=blocking_ranges,json=blockingRanges,proto3" json:"blocking_ranges,omitempty"`
	CurrentServerAckedThrough *Cursor                `protobuf:"bytes,4,opt,name=current_server_acked_through,json=currentServerAckedThrough,proto3" json:"current_server_acked_through,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AckResult) Reset() {
	*x = AckResult{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResult) ProtoMessage() {}

func (x *AckResult) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResult.ProtoReflect.Descriptor instead.
func (*AckResult) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{14}
}

func (x *AckResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AckResult) GetSnapshot() *AuditCoverageSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *AckResult) GetBlockingRanges() []*CoverageRange {
	if x != nil {
		return x.BlockingRanges
	}
	return nil
}

func (x *AckResult) GetCurrentServerAckedThrough() *Cursor {
	if x != nil {
		return x.CurrentServerAckedThrough
	}
	return nil
}

type CoverageRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incarnation   uint64                 `protobuf:"varint,1,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	ToSeq         uint64                 `protobuf:"varint,3,opt,name=to_seq,json=toSeq,proto3" json:"to_seq,omitempty"`
	Reason        GapReason              `protobuf:"varint,4,opt,name=reason,proto3,enum=docklattice.prototype.v1.GapReason" json:"reason,omitempty"`
	Precision     Precision              `protobuf:"varint,5,opt,name=precision,proto3,enum=docklattice.prototype.v1.Precision" json:"precision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverageRange) Reset() {
	*x = CoverageRange{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverageRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverageRange) ProtoMessage() {}

func (x *CoverageRange) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverageRange.ProtoReflect.Descriptor instead.
func (*CoverageRange) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{15}
}

func (x *CoverageRange) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *CoverageRange) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *CoverageRange) GetToSeq() uint64 {
	if x != nil {
		return x.ToSeq
	}
	return 0
}

func (x *CoverageRange) GetReason() GapReason {
	if x != nil {
		return x.Reason
	}
	return GapReason_GAP_REASON_UNSPECIFIED
}

func (x *CoverageRange) GetPrecision() Precision {
	if x != nil {
		return x.Precision
	}
	return Precision_PRECISION_UNSPECIFIED
}

type GetAuditCoverageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditCoverageRequest) Reset() {
	*x = GetAuditCoverageRequest{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditCoverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditCoverageRequest) ProtoMessage() {}

func (x *GetAuditCoverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditCoverageRequest.ProtoReflect.Descriptor instead.
func (*GetAuditCoverageRequest) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{16}
}

type AuditCoverageSnapshot struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	AgentId                     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CoverageRevision            uint64                 `protobuf:"varint,2,opt,name=coverage_revision,json=coverageRevision,proto3" json:"coverage_revision,omitempty"`
	GeneratedAtUnixNano         int64                  `protobuf:"varint,3,opt,name=generated_at_unix_nano,json=generatedAtUnixNano,proto3" json:"generated_at_unix_nano,omitempty"`
	Gaps                        []*CoverageRange       `protobuf:"bytes,4,rep,name=gaps,proto3" json:"gaps,omitempty"`
	CoverageUnknownIncarnations []uint64               `protobuf:"varint,5,rep,packed,name=coverage_unknown_incarnations,json=coverageUnknownIncarnations,proto3" json:"coverage_unknown_incarnations,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AuditCoverageSnapshot) Reset() {
	*x = AuditCoverageSnapshot{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditCoverageSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditCoverageSnapshot) ProtoMessage() {}

func (x *AuditCoverageSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditCoverageSnapshot.ProtoReflect.Descriptor instead.
func (*AuditCoverageSnapshot) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{17}
}

func (x *AuditCoverageSnapshot) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AuditCoverageSnapshot) GetCoverageRevision() uint64 {
	if x != nil {
		return x.CoverageRevision
	}
	return 0
}

func (x *AuditCoverageSnapshot) GetGeneratedAtUnixNano() int64 {
	if x != nil {
		return x.GeneratedAtUnixNano
	}
	return 0
}

func (x *AuditCoverageSnapshot) GetGaps() []*CoverageRange {
	if x != nil {
		return x.Gaps
	}
	return nil
}

func (x *AuditCoverageSnapshot) GetCoverageUnknownIncarnations() []uint64 {
	if x != nil {
		return x.CoverageUnknownIncarnations
	}
	return nil
}

// Echo는 Docker query를 대체하는 지연 측정용 요청이다(부록 A.4).
type EchoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PayloadSize    uint32                 `protobuf:"varint,1,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	SentAtUnixNano int64                  `protobuf:"varint,2,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{18}
}

func (x *EchoRequest) GetPayloadSize() uint32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *EchoRequest) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

type EchoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Payload        []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SentAtUnixNano int64                  `protobuf:"varint,2,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{19}
}

func (x *EchoResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EchoResponse) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

type StreamLogsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// byte_rate는 합성 부하 생성률이다(bytes/sec).
	ByteRate      uint32 `protobuf:"varint,2,opt,name=byte_rate,json=byteRate,proto3" json:"byte_rate,omitempty"`
	LineSize      uint32 `protobuf:"varint,3,opt,name=line_size,json=lineSize,proto3" json:"line_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{20}
}

func (x *StreamLogsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamLogsRequest) GetByteRate() uint32 {
	if x != nil {
		return x.ByteRate
	}
	return 0
}

func (x *StreamLogsRequest) GetLineSize() uint32 {
	if x != nil {
		return x.LineSize
	}
	return 0
}

type LogChunk struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StreamId          string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq               uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	EmittedAtUnixNano int64                  `protobuf:"varint,3,opt,name=emitted_at_unix_nano,json=emittedAtUnixNano,proto3" json:"emitted_at_unix_nano,omitempty"`
	Data              []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// dropped_bytes는 느린 소비자 때문에 생략한 바이트다. 조용히 버리지
	// 않고 명시한다(ADR §5.2).
	DroppedBytes  uint64 `protobuf:"varint,5,opt,name=dropped_bytes,json=droppedBytes,proto3" json:"dropped_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{21}
}

func (x *LogChunk) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *LogChunk) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogChunk) GetEmittedAtUnixNano() int64 {
	if x != nil {
		return x.EmittedAtUnixNano
	}
	return 0
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetDroppedBytes() uint64 {
	if x != nil {
		return x.DroppedBytes
	}
	return 0
}

type OperationOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationOutputRequest) Reset() {
	*x = OperationOutputRequest{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationOutputRequest) ProtoMessage() {}

func (x *OperationOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationOutputRequest.ProtoReflect.Descriptor instead.
func (*OperationOutputRequest) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{22}
}

func (x *OperationOutputRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type OperationOutputChunk struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationId       string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Seq               uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	EmittedAtUnixNano int64                  `protobuf:"varint,3,opt,name=emitted_at_unix_nano,json=emittedAtUnixNano,proto3" json:"emitted_at_unix_nano,omitempty"`
	Data              []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Truncated         bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OperationOutputChunk) Reset() {
	*x = OperationOutputChunk{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationOutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationOutputChunk) ProtoMessage() {}

func (x *OperationOutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationOutputChunk.ProtoReflect.Descriptor instead.
func (*OperationOutputChunk) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{23}
}

func (x *OperationOutputChunk) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationOutputChunk) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *OperationOutputChunk) GetEmittedAtUnixNano() int64 {
	if x != nil {
		return x.EmittedAtUnixNano
	}
	return 0
}

func (x *OperationOutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OperationOutputChunk) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type StreamStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []string               `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	IntervalMs    uint32                 `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatsRequest) Reset() {
	*x = StreamStatsRequest{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatsRequest) ProtoMessage() {}

func (x *StreamStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatsRequest.ProtoReflect.Descriptor instead.
func (*StreamStatsRequest) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{24}
}

func (x *StreamStatsRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *StreamStatsRequest) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type StatsSample struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Target            string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	SampledAtUnixNano int64                  `protobuf:"varint,2,opt,name=sampled_at_unix_nano,json=sampledAtUnixNano,proto3" json:"sampled_at_unix_nano,omitempty"`
	CpuPercent        float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes       uint64                 `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	MemoryLimitBytes  uint64                 `protobuf:"varint,5,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	NetRxBytes        uint64                 `protobuf:"varint,6,opt,name=net_rx_bytes,json=netRxBytes,proto3" json:"net_rx_bytes,omitempty"`
	NetTxBytes        uint64                 `protobuf:"varint,7,opt,name=net_tx_bytes,json=netTxBytes,proto3" json:"net_tx_bytes,omitempty"`
	BlockReadBytes    uint64                 `protobuf:"varint,8,opt,name=block_read_bytes,json=blockReadBytes,proto3" json:"block_read_bytes,omitempty"`
	BlockWriteBytes   uint64                 `protobuf:"varint,9,opt,name=block_write_bytes,json=blockWriteBytes,proto3" json:"block_write_bytes,omitempty"`
	Padding           []byte                 `protobuf:"bytes,10,opt,name=padding,proto3" json:"padding,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatsSample) Reset() {
	*x = StatsSample{}
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsSample) ProtoMessage() {}

func (x *StatsSample) ProtoReflect() protoreflect.Message {
	mi := &file_docklattice_prototype_v1_contract_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsSample.ProtoReflect.Descriptor instead.
func (*StatsSample) Descriptor() ([]byte, []int) {
	return file_docklattice_prototype_v1_contract_proto_rawDescGZIP(), []int{25}
}

func (x *StatsSample) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *StatsSample) GetSampledAtUnixNano() int64 {
	if x != nil {
		return x.SampledAtUnixNano
	}
	return 0
}

func (x *StatsSample) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *StatsSample) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *StatsSample) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *StatsSample) GetNetRxBytes() uint64 {
	if x != nil {
		return x.NetRxBytes
	}
	return 0
}

func (x *StatsSample) GetNetTxBytes() uint64 {
	if x != nil {
		return x.NetTxBytes
	}
	return 0
}

func (x *StatsSample) GetBlockReadBytes() uint64 {
	if x != nil {
		return x.BlockReadBytes
	}
	return 0
}

func (x *StatsSample) GetBlockWriteBytes() uint64 {
	if x != nil {
		return x.BlockWriteBytes
	}
	return 0
}

func (x *StatsSample) GetPadding() []byte {
	if x != nil {
		return x.Padding
	}
	return nil
}

var File_docklattice_prototype_v1_contract_proto protoreflect.FileDescriptor

const file_docklattice_prototype_v1_contract_proto_rawDesc = "" +
	"\n" +
	"'docklattice/prototype/v1/contract.proto\x12\x18docklattice.prototype.v1\"W\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\"\xa2\x01\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12D\n" +
	"\n" +
	"capability\x18\x03 \x01(\v2$.docklattice.prototype.v1.CapabilityR\n" +
	"capability\"=\n" +
	"\x10HeartbeatRequest\x12)\n" +
	"\x11sent_at_unix_nano\x18\x01 \x01(\x03R\x0esentAtUnixNano\"\x84\x01\n" +
	"\x11HeartbeatResponse\x12)\n" +
	"\x11sent_at_unix_nano\x18\x01 \x01(\x03R\x0esentAtUnixNano\x12D\n" +
	"\n" +
	"capability\x18\x02 \x01(\v2$.docklattice.prototype.v1.CapabilityR\n" +
	"capability\"\xb0\x01\n" +
	"\n" +
	"Capability\x12\x19\n" +
	"\bfs_write\x18\x01 \x01(\bR\afsWrite\x12!\n" +
	"\fcompose_exec\x18\x02 \x01(\bR\vcomposeExec\x126\n" +
	"\x17bundled_compose_version\x18\x03 \x01(\tR\x15bundledComposeVersion\x12,\n" +
	"\x12docker_api_version\x18\x04 \x01(\tR\x10dockerApiVersion\"{\n" +
	"\x16CancelOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12>\n" +
	"\x06reason\x18\x02 \x01(\x0e2&.docklattice.prototype.v1.CancelReasonR\x06reason\"\x8e\x01\n" +
	"\x17CancelOperationResponse\x12>\n" +
	"\x06result\x18\x01 \x01(\x0e2&.docklattice.prototype.v1.CancelResultR\x06result\x123\n" +
	"\x16requested_at_unix_nano\x18\x02 \x01(\x03R\x13requestedAtUnixNano\"\x1a\n" +
	"\x18OperationProgressRequest\"\x81\x03\n" +
	"\x16OperationProgressEvent\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12-\n" +
	"\x12operation_revision\x18\x02 \x01(\x04R\x11operationRevision\x12>\n" +
	"\x05phase\x18\x03 \x01(\x0e2(.docklattice.prototype.v1.OperationPhaseR\x05phase\x12E\n" +
	"\vcancel_mode\x18\x04 \x01(\x0e2$.docklattice.prototype.v1.CancelModeR\n" +
	"cancelMode\x121\n" +
	"\x15occurred_at_unix_nano\x18\x05 \x01(\x03R\x12occurredAtUnixNano\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12\x1a\n" +
	"\bterminal\x18\a \x01(\bR\bterminal\x12'\n" +
	"\x0fterminal_status\x18\b \x01(\tR\x0eterminalStatus\"<\n" +
	"\x06Cursor\x12 \n" +
	"\vincarnation\x18\x01 \x01(\x04R\vincarnation\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"\xbd\x01\n" +
	"\vAuditRecord\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x04R\vincarnation\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x121\n" +
	"\x15occurred_at_unix_nano\x18\x04 \x01(\x03R\x12occurredAtUnixNano\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"\xf9\x01\n" +
	"\x10SyncAuditMessage\x12?\n" +
	"\x06record\x18\x01 \x01(\v2%.docklattice.prototype.v1.AuditRecordH\x00R\x06record\x12V\n" +
	"\x10coverage_changed\x18\x02 \x01(\v2).docklattice.prototype.v1.CoverageChangedH\x00R\x0fcoverageChanged\x12D\n" +
	"\n" +
	"ack_result\x18\x03 \x01(\v2#.docklattice.prototype.v1.AckResultH\x00R\tackResultB\x06\n" +
	"\x04body\">\n" +
	"\x0fCoverageChanged\x12+\n" +
	"\x11coverage_revision\x18\x01 \x01(\x04R\x10coverageRevision\"\xa8\x01\n" +
	"\fSyncAuditAck\x12(\n" +
	"\x10audit_archive_id\x18\x01 \x01(\tR\x0eauditArchiveId\x128\n" +
	"\x06cursor\x18\x02 \x01(\v2 .docklattice.prototype.v1.CursorR\x06cursor\x124\n" +
	"\x16coverage_revision_seen\x18\x03 \x01(\x04R\x14coverageRevisionSeen\"\xa9\x02\n" +
	"\tAckResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12K\n" +
	"\bsnapshot\x18\x02 \x01(\v2/.docklattice.prototype.v1.AuditCoverageSnapshotR\bsnapshot\x12P\n" +
	"\x0fblocking_ranges\x18\x03 \x03(\v2'.docklattice.prototype.v1.CoverageRangeR\x0eblockingRanges\x12a\n" +
	"\x1ccurrent_server_acked_through\x18\x04 \x01(\v2 .docklattice.prototype.v1.CursorR\x19currentServerAckedThrough\"\xe3\x01\n" +
	"\rCoverageRange\x12 \n" +
	"\vincarnation\x18\x01 \x01(\x04R\vincarnation\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\x12\x15\n" +
	"\x06to_seq\x18\x03 \x01(\x04R\x05toSeq\x12;\n" +
	"\x06reason\x18\x04 \x01(\x0e2#.docklattice.prototype.v1.GapReasonR\x06reason\x12A\n" +
	"\tprecision\x18\x05 \x01(\x0e2#.docklattice.prototype.v1.PrecisionR\tprecision\"\x19\n" +
	"\x17GetAuditCoverageRequest\"\x95\x02\n" +
	"\x15AuditCoverageSnapshot\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12+\n" +
	"\x11coverage_revision\x18\x02 \x01(\x04R\x10coverageRevision\x123\n" +
	"\x16generated_at_unix_nano\x18\x03 \x01(\x03R\x13generatedAtUnixNano\x12;\n" +
	"\x04gaps\x18\x04 \x03(\v2'.docklattice.prototype.v1.CoverageRangeR\x04gaps\x12B\n" +
	"\x1dcoverage_unknown_incarnations\x18\x05 \x03(\x04R\x1bcoverageUnknownIncarnations\"[\n" +
	"\vEchoRequest\x12!\n" +
	"\fpayload_size\x18\x01 \x01(\rR\vpayloadSize\x12)\n" +
	"\x11sent_at_unix_nano\x18\x02 \x01(\x03R\x0esentAtUnixNano\"S\n" +
	"\fEchoResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12)\n" +
	"\x11sent_at_unix_nano\x18\x02 \x01(\x03R\x0esentAtUnixNano\"j\n" +
	"\x11StreamLogsRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1b\n" +
	"\tbyte_rate\x18\x02 \x01(\rR\bbyteRate\x12\x1b\n" +
	"\tline_size\x18\x03 \x01(\rR\blineSize\"\xa3\x01\n" +
	"\bLogChunk\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12/\n" +
	"\x14emitted_at_unix_nano\x18\x03 \x01(\x03R\x11emittedAtUnixNano\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12#\n" +
	"\rdropped_bytes\x18\x05 \x01(\x04R\fdroppedBytes\";\n" +
	"\x16OperationOutputRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"\xae\x01\n" +
	"\x14OperationOutputChunk\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12/\n" +
	"\x14emitted_at_unix_nano\x18\x03 \x01(\x03R\x11emittedAtUnixNano\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\"O\n" +
	"\x12StreamStatsRequest\x12\x18\n" +
	"\atargets\x18\x01 \x03(\tR\atargets\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\rR\n" +
	"intervalMs\"\xfc\x02\n" +
	"\vStatsSample\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12/\n" +
	"\x14sampled_at_unix_nano\x18\x02 \x01(\x03R\x11sampledAtUnixNano\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x04R\vmemoryBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x05 \x01(\x04R\x10memoryLimitBytes\x12 \n" +
	"\fnet_rx_bytes\x18\x06 \x01(\x04R\n" +
	"netRxBytes\x12 \n" +
	"\fnet_tx_bytes\x18\a \x01(\x04R\n" +
	"netTxBytes\x12(\n" +
	"\x10block_read_bytes\x18\b \x01(\x04R\x0eblockReadBytes\x12*\n" +
	"\x11block_write_bytes\x18\t \x01(\x04R\x0fblockWriteBytes\x12\x18\n" +
	"\apadding\x18\n" +
	" \x01(\fR\apadding*\x82\x01\n" +
	"\fCancelReason\x12\x1d\n" +
	"\x19CANCEL_REASON_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CANCEL_REASON_USER\x10\x01\x12\x19\n" +
	"\x15CANCEL_REASON_TIMEOUT\x10\x02\x12 \n" +
	"\x1cCANCEL_REASON_AGENT_SHUTDOWN\x10\x03*\xc8\x01\n" +
	"\fCancelResult\x12\x1d\n" +
	"\x19CANCEL_RESULT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CANCEL_RESULT_ACCEPTED\x10\x01\x12\x1a\n" +
	"\x16CANCEL_RESULT_TOO_LATE\x10\x02\x12 \n" +
	"\x1cCANCEL_RESULT_NOT_CANCELABLE\x10\x03\x12\"\n" +
	"\x1eCANCEL_RESULT_ALREADY_TERMINAL\x10\x04\x12\x1b\n" +
	"\x17CANCEL_RESULT_NOT_FOUND\x10\x05*\xcd\x01\n" +
	"\x0eOperationPhase\x12\x1f\n" +
	"\x1bOPERATION_PHASE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19OPERATION_PHASE_PREPARING\x10\x01\x12\x1d\n" +
	"\x19OPERATION_PHASE_EXECUTING\x10\x02\x12\x1e\n" +
	"\x1aOPERATION_PHASE_COMMITTING\x10\x03\x12\x1e\n" +
	"\x1aOPERATION_PHASE_FINALIZING\x10\x04\x12\x1c\n" +
	"\x18OPERATION_PHASE_TERMINAL\x10\x05*\x83\x01\n" +
	"\n" +
	"CancelMode\x12\x1b\n" +
	"\x17CANCEL_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CANCEL_MODE_SAFE\x10\x01\x12#\n" +
	"\x1fCANCEL_MODE_BEST_EFFORT_PARTIAL\x10\x02\x12\x1d\n" +
	"\x19CANCEL_MODE_BEFORE_COMMIT\x10\x03*_\n" +
	"\tGapReason\x12\x1a\n" +
	"\x16GAP_REASON_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14GAP_REASON_RETENTION\x10\x01\x12\x1c\n" +
	"\x18GAP_REASON_DISK_PRESSURE\x10\x02*T\n" +
	"\tPrecision\x12\x19\n" +
	"\x15PRECISION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPRECISION_EXACT\x10\x01\x12\x17\n" +
	"\x13PRECISION_COALESCED\x10\x02B:Z8github.com/east-true/docklattice/internal/contract/pb;pbb\x06proto3"

var (
	file_docklattice_prototype_v1_contract_proto_rawDescOnce sync.Once
	file_docklattice_prototype_v1_contract_proto_rawDescData []byte
)

func file_docklattice_prototype_v1_contract_proto_rawDescGZIP() []byte {
	file_docklattice_prototype_v1_contract_proto_rawDescOnce.Do(func() {
		file_docklattice_prototype_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docklattice_prototype_v1_contract_proto_rawDesc), len(file_docklattice_prototype_v1_contract_proto_rawDesc)))
	})
	return file_docklattice_prototype_v1_contract_proto_rawDescData
}

var file_docklattice_prototype_v1_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_docklattice_prototype_v1_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_docklattice_prototype_v1_contract_proto_goTypes = []any{
	(CancelReason)(0),                // 0: docklattice.prototype.v1.CancelReason
	(CancelResult)(0),                // 1: docklattice.prototype.v1.CancelResult
	(OperationPhase)(0),              // 2: docklattice.prototype.v1.OperationPhase
	(CancelMode)(0),                  // 3: docklattice.prototype.v1.CancelMode
	(GapReason)(0),                   // 4: docklattice.prototype.v1.GapReason
	(Precision)(0),                   // 5: docklattice.prototype.v1.Precision
	(*RegisterRequest)(nil),          // 6: docklattice.prototype.v1.RegisterRequest
	(*RegisterResponse)(nil),         // 7: docklattice.prototype.v1.RegisterResponse
	(*HeartbeatRequest)(nil),         // 8: docklattice.prototype.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 9: docklattice.prototype.v1.HeartbeatResponse
	(*Capability)(nil),               // 10: docklattice.prototype.v1.Capability
	(*CancelOperationRequest)(nil),   // 11: docklattice.prototype.v1.CancelOperationRequest
	(*CancelOperationResponse)(nil),  // 12: docklattice.prototype.v1.CancelOperationResponse
	(*OperationProgressRequest)(nil), // 13: docklattice.prototype.v1.OperationProgressRequest
	(*OperationProgressEvent)(nil),   // 14: docklattice.prototype.v1.OperationProgressEvent
	(*Cursor)(nil),                   // 15: docklattice.prototype.v1.Cursor
	(*AuditRecord)(nil),              // 16: docklattice.prototype.v1.AuditRecord
	(*SyncAuditMessage)(nil),         // 17: docklattice.prototype.v1.SyncAuditMessage
	(*CoverageChanged)(nil),          // 18: docklattice.prototype.v1.CoverageChanged
	(*SyncAuditAck)(nil),             // 19: docklattice.prototype.v1.SyncAuditAck
	(*AckResult)(nil),                // 20: docklattice.prototype.v1.AckResult
	(*CoverageRange)(nil),            // 21: docklattice.prototype.v1.CoverageRange
	(*GetAuditCoverageRequest)(nil),  // 22: docklattice.prototype.v1.GetAuditCoverageRequest
	(*AuditCoverageSnapshot)(nil),    // 23: docklattice.prototype.v1.AuditCoverageSnapshot
	(*EchoRequest)(nil),              // 24: docklattice.prototype.v1.EchoRequest
	(*EchoResponse)(nil),             // 25: docklattice.prototype.v1.EchoResponse
	(*StreamLogsRequest)(nil),        // 26: docklattice.prototype.v1.StreamLogsRequest
	(*LogChunk)(nil),                 // 27: docklattice.prototype.v1.LogChunk
	(*OperationOutputRequest)(nil),   // 28: docklattice.prototype.v1.OperationOutputRequest
	(*OperationOutputChunk)(nil),     // 29: docklattice.prototype.v1.OperationOutputChunk
	(*StreamStatsRequest)(nil),       // 30: docklattice.prototype.v1.StreamStatsRequest
	(*StatsSample)(nil),              // 31: docklattice.prototype.v1.StatsSample
}
var file_docklattice_prototype_v1_contract_proto_depIdxs = []int32{
	10, // 0: docklattice.prototype.v1.RegisterResponse.capability:type_name -> docklattice.prototype.v1.Capability
	10, // 1: docklattice.prototype.v1.HeartbeatResponse.capability:type_name -> docklattice.prototype.v1.Capability
	0,  // 2: docklattice.prototype.v1.CancelOperationRequest.reason:type_name -> docklattice.prototype.v1.CancelReason
	1,  // 3: docklattice.prototype.v1.CancelOperationResponse.result:type_name -> docklattice.prototype.v1.CancelResult
	2,  // 4: docklattice.prototype.v1.OperationProgressEvent.phase:type_name -> docklattice.prototype.v1.OperationPhase
	3,  // 5: docklattice.prototype.v1.OperationProgressEvent.cancel_mode:type_name -> docklattice.prototype.v1.CancelMode
	16, // 6: docklattice.prototype.v1.SyncAuditMessage.record:type_name -> docklattice.prototype.v1.AuditRecord
	18, // 7: docklattice.prototype.v1.SyncAuditMessage.coverage_changed:type_name -> docklattice.prototype.v1.CoverageChanged
	20, // 8: docklattice.prototype.v1.SyncAuditMessage.ack_result:type_name -> docklattice.prototype.v1.AckResult
	15, // 9: docklattice.prototype.v1.SyncAuditAck.cursor:type_name -> docklattice.prototype.v1.Cursor
	23, // 10: docklattice.prototype.v1.AckResult.snapshot:type_name -> docklattice.prototype.v1.AuditCoverageSnapshot
	21, // 11: docklattice.prototype.v1.AckResult.blocking_ranges:type_name -> docklattice.prototype.v1.CoverageRange
	15, // 12: docklattice.prototype.v1.AckResult.current_server_acked_through:type_name -> docklattice.prototype.v1.Cursor
	4,  // 13: docklattice.prototype.v1.CoverageRange.reason:type_name -> docklattice.prototype.v1.GapReason
	5,  // 14: docklattice.prototype.v1.CoverageRange.precision:type_name -> docklattice.prototype.v1.Precision
	21, // 15: docklattice.prototype.v1.AuditCoverageSnapshot.gaps:type_name -> docklattice.prototype.v1.CoverageRange
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_docklattice_prototype_v1_contract_proto_init() }
func file_docklattice_prototype_v1_contract_proto_init() {
	if File_docklattice_prototype_v1_contract_proto != nil {
		return
	}
	file_docklattice_prototype_v1_contract_proto_msgTypes[11].OneofWrappers = []any{
		(*SyncAuditMessage_Record)(nil),
		(*SyncAuditMessage_CoverageChanged)(nil),
		(*SyncAuditMessage_AckResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docklattice_prototype_v1_contract_proto_rawDesc), len(file_docklattice_prototype_v1_contract_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_docklattice_prototype_v1_contract_proto_goTypes,
		DependencyIndexes: file_docklattice_prototype_v1_contract_proto_depIdxs,
		EnumInfos:         file_docklattice_prototype_v1_contract_proto_enumTypes,
		MessageInfos:      file_docklattice_prototype_v1_contract_proto_msgTypes,
	}.Build()
	File_docklattice_prototype_v1_contract_proto = out.File
	file_docklattice_prototype_v1_contract_proto_goTypes = nil
	file_docklattice_prototype_v1_contract_proto_depIdxs = nil
}
