// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dockpilot/prototype/grpc/v1/wire.proto

// This schema is private to Candidate A. None of these HTTP/2/gRPC adapter
// details are exposed by the transport-neutral package.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    uint64                 `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Kind          uint32                 `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
	TrafficClass  uint32                 `protobuf:"varint,4,opt,name=traffic_class,json=trafficClass,proto3" json:"traffic_class,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_dockpilot_prototype_grpc_v1_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_prototype_grpc_v1_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_dockpilot_prototype_grpc_v1_wire_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetExchangeId() uint64 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *OpenRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OpenRequest) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *OpenRequest) GetTrafficClass() uint32 {
	if x != nil {
		return x.TrafficClass
	}
	return 0
}

func (x *OpenRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type UnaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryResponse) Reset() {
	*x = UnaryResponse{}
	mi := &file_dockpilot_prototype_grpc_v1_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryResponse) ProtoMessage() {}

func (x *UnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_prototype_grpc_v1_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryResponse.ProtoReflect.Descriptor instead.
func (*UnaryResponse) Descriptor() ([]byte, []int) {
	return file_dockpilot_prototype_grpc_v1_wire_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StreamFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*StreamFrame_Open
	//	*StreamFrame_Payload
	Body          isStreamFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFrame) Reset() {
	*x = StreamFrame{}
	mi := &file_dockpilot_prototype_grpc_v1_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFrame) ProtoMessage() {}

func (x *StreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_dockpilot_prototype_grpc_v1_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFrame.ProtoReflect.Descriptor instead.
func (*StreamFrame) Descriptor() ([]byte, []int) {
	return file_dockpilot_prototype_grpc_v1_wire_proto_rawDescGZIP(), []int{2}
}

func (x *StreamFrame) GetBody() isStreamFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StreamFrame) GetOpen() *OpenRequest {
	if x != nil {
		if x, ok := x.Body.(*StreamFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *StreamFrame) GetPayload() []byte {
	if x != nil {
		if x, ok := x.Body.(*StreamFrame_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isStreamFrame_Body interface {
	isStreamFrame_Body()
}

type StreamFrame_Open struct {
	Open *OpenRequest `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type StreamFrame_Payload struct {
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

func (*StreamFrame_Open) isStreamFrame_Body() {}

func (*StreamFrame_Payload) isStreamFrame_Body() {}

var File_dockpilot_prototype_grpc_v1_wire_proto protoreflect.FileDescriptor

const file_dockpilot_prototype_grpc_v1_wire_proto_rawDesc = "" +
	"\n" +
	"&dockpilot/prototype/grpc/v1/wire.proto\x12\x1bdockpilot.prototype.grpc.v1\"\x99\x01\n" +
	"\vOpenRequest\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x04R\n" +
	"exchangeId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\rR\x04kind\x12#\n" +
	"\rtraffic_class\x18\x04 \x01(\rR\ftrafficClass\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\")\n" +
	"\rUnaryResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"q\n" +
	"\vStreamFrame\x12>\n" +
	"\x04open\x18\x01 \x01(\v2(.dockpilot.prototype.grpc.v1.OpenRequestH\x00R\x04open\x12\x1a\n" +
	"\apayload\x18\x02 \x01(\fH\x00R\apayloadB\x06\n" +
	"\x04bodyBEZCgithub.com/east-true/dockpilot/internal/candidate/grpcadapter/pb;pbb\x06proto3"

var (
	file_dockpilot_prototype_grpc_v1_wire_proto_rawDescOnce sync.Once
	file_dockpilot_prototype_grpc_v1_wire_proto_rawDescData []byte
)

func file_dockpilot_prototype_grpc_v1_wire_proto_rawDescGZIP() []byte {
	file_dockpilot_prototype_grpc_v1_wire_proto_rawDescOnce.Do(func() {
		file_dockpilot_prototype_grpc_v1_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dockpilot_prototype_grpc_v1_wire_proto_rawDesc), len(file_dockpilot_prototype_grpc_v1_wire_proto_rawDesc)))
	})
	return file_dockpilot_prototype_grpc_v1_wire_proto_rawDescData
}

var file_dockpilot_prototype_grpc_v1_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dockpilot_prototype_grpc_v1_wire_proto_goTypes = []any{
	(*OpenRequest)(nil),   // 0: dockpilot.prototype.grpc.v1.OpenRequest
	(*UnaryResponse)(nil), // 1: dockpilot.prototype.grpc.v1.UnaryResponse
	(*StreamFrame)(nil),   // 2: dockpilot.prototype.grpc.v1.StreamFrame
}
var file_dockpilot_prototype_grpc_v1_wire_proto_depIdxs = []int32{
	0, // 0: dockpilot.prototype.grpc.v1.StreamFrame.open:type_name -> dockpilot.prototype.grpc.v1.OpenRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dockpilot_prototype_grpc_v1_wire_proto_init() }
func file_dockpilot_prototype_grpc_v1_wire_proto_init() {
	if File_dockpilot_prototype_grpc_v1_wire_proto != nil {
		return
	}
	file_dockpilot_prototype_grpc_v1_wire_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamFrame_Open)(nil),
		(*StreamFrame_Payload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dockpilot_prototype_grpc_v1_wire_proto_rawDesc), len(file_dockpilot_prototype_grpc_v1_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dockpilot_prototype_grpc_v1_wire_proto_goTypes,
		DependencyIndexes: file_dockpilot_prototype_grpc_v1_wire_proto_depIdxs,
		MessageInfos:      file_dockpilot_prototype_grpc_v1_wire_proto_msgTypes,
	}.Build()
	File_dockpilot_prototype_grpc_v1_wire_proto = out.File
	file_dockpilot_prototype_grpc_v1_wire_proto_goTypes = nil
	file_dockpilot_prototype_grpc_v1_wire_proto_depIdxs = nil
}
